### ISSUE TITLE
Internal Server Error if no entities specified (version 2.0)

### ISSUE THREAD

**Issue by comet424** [arthurdent75/SimpleScheduler#101]
with the last update of HA  which is the .5  i dunno something has broken simple scheduler..

i get this error on the simple scheduler page 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

now if i remove my last entry of the .json file for one of my schedulers..  the  internal server error is gone my other schedules  show up
but i can no longer  click +  button to create another   you cant move them up and down  you cant edit them or toggle the display for them...  i did a full back up and did a new install of HA and did a full restore that didnt fix it.. if i put the last json file back in  it gives the internal server error

i looked at simple schedule logs   and nothing there and no real issues in the HA well i dunno what id be looking for..

anything thats causing it  ? any way i can fix it   its only doing this to the Simple Scheduler..        
esphome, nodered  ad guard  they all seem to work fine   just simple scheduler isnt

i have unsinstalled  uninstalled respository    did nothing and it gave error to install  simple scheduler
if i didnt have the simple scheduler folder in the share folder...  i had to create that folder first to get it to even try to install  so i not sure if you come across this and or know how i can get it up and working again

ive tried 3 different browswers and it does it to all 3.. so its not specific

and the last file that causes the internal corruption is 

```{"id":"62685702994be","name":"Grow Light 3","enabled":0,"entity_id":null,"on_tod":"19:00","on_dow":"1234567","off_tod":"13:00","off_dow":"1234567"}```

**Comment by comet424** [comment]
some logs from the scheduler.log     but the log under logs  shows nothing  so under simple scheduler log tab  never shows anything  just hte log file

and some of it is 
```[2022-12-02 15:37:23] STATUS: Starting WebServer
[2022-12-02 15:37:26] STATUS: Starting scheduler
[2022-12-02 16:45:00] ERROR: Unable to obtain entities names from Home Assistant
[2022-12-02 16:49:22] STATUS: Starting main program
[2022-12-02 16:49:27] ERROR: Unable to obtain timezone from Home Assistant
[2022-12-02 16:49:27] STATUS: Starting WebServer
[2022-12-02 16:49:30] STATUS: Starting scheduler
[2022-12-02 16:57:00] ERROR: Unable to obtain entities names from Home Assistant
[2022-12-02 17:01:32] STATUS: Starting main program
[2022-12-02 17:01:37] STATUS: Starting WebServer
[2022-12-02 17:01:40] STATUS: Starting scheduler
[2022-12-02 17:21:35] STATUS: Starting main program
[2022-12-02 17:21:40] ERROR: Unable to obtain timezone from Home Assistant
[2022-12-02 17:21:40] STATUS: Starting WebServer
[2022-12-02 17:21:44] STATUS: Starting scheduler
[2022-12-02 17:29:54] STATUS: Starting main program
[2022-12-02 17:30:00] ERROR: Unable to obtain timezone from Home Assistant
[2022-12-02 17:30:00] STATUS: Starting WebServer
[2022-12-02 17:30:03] STATUS: Starting scheduler
```

**Comment by arthurdent75** [comment]
> {"id":"62685702994be","name":"Grow Light 3","enabled":0,**"entity_id":null**,"on_tod":"19:00","on_dow":"1234567","off_tod":"13:00","off_dow":"1234567"}

This is the reason: there is no entity associated in this scheduler.
This is surely a situation to manage in the new release.

**Comment by comet424** [comment]
i tried uninstalling  different things i no longer use...  i still cant get the + to add a new schedule...  i have 2 other HA with your great addon..  they seem to work..  but on my main  HA   i not sure whats going on.. the logs i can only read from the actual log file  if  i goto  system---logs---simple schedule  it shows nothing  same under add on simple scheduler  logs...   as i cant figure how to get it to work again....  frustrated   cuz i can figure it out... and thats after i found i had this interneral error..  where devices stopped triggering at there certain times....  not sure if something else is stopping it?

**Comment by arthurdent75** [comment]
Downgrade to 0.64 (it works now)
Should solve everything

**Comment by comet424** [comment]
not sure how to do that

**Comment by comet424** [comment]
oh i see its an upgrade button i though i had to find a downgrade button  ill try   now

**Comment by comet424** [comment]
it worked  thank you very much ...  its back to working  and null one i guess thats cuz i removed  old plug and renamed it.. for another thing   but have the schedule  disabled  as i wasnt using it  but till a later date..

thank you..  i was going nuts  how it worked on my other 2 HA  but they have hardly anything installed couldnt figure why there + worked but the main one that has bunch of stuff installed didnt work.. figured an app or a setting was corrupting things

thanks for fixing  i appreciate it (👍
