### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by akalderon** [arthurdent75/SimpleScheduler#102]
Upgrade from 0.64 to 2.015 failed. I uninstalled 0.64 and did a fresh install of 2.015 to find a failure with the following message:

The command '/bin/sh -c pip3 install Flask requests paho-mqtt pytz slugify psutil' returned a non-zero code: 1

**Comment by Anders-Falk** [comment]
Got the same error on RPi4 with Homeassistant

**Comment by rjenx** [comment]
Me 2

**Comment by Andream69** [comment]
Idem stesso problema

**Comment by arthurdent75** [comment]
duplicate #96

**Comment by rjenx** [comment]
I don't understand the solution proposed, other than it appears a particular progam is misisng from debian. The solution I have seen does not fix it permanently for me as I run HA on Yellow. As soon as this gets an update I assume this will undue any changes to the operating system without you working with the Yellow team to fix this issue permanently.

**Comment by Anders-Falk** [comment]
Just reinstall. The version published is reverted back to 0.64

**Comment by rjenx** [comment]
Thanks,
