### ISSUE TITLE
Cannot delete entity in Schedule

### ISSUE THREAD

**Issue by Builder-DE-TH** [arthurdent75/SimpleScheduler#103]
When you click on the red bin icon the entity does not delete.
These are schedules created using the old version (0.64)

**Comment by arthurdent75** [comment]
This issue are no longer present in the new release 2.0 that is about to be published.
If you are an HA advanced user and you want to try it as beta tester add this repository:

https://github.com/arthurdent75/SimpleScheduler-BETA
