### ISSUE TITLE
Docker container fails to start second time

### ISSUE THREAD

**Issue by mcalahan** [arthurdent75/SimpleScheduler#104]
Restart fails as /var/www/html/index.html doesn't exist and /etc/conf-init.d/simplescheduler.sh doesn't succeed.

Work around I applied is to add -f to the rm command:
line 6 : 
 rm -f /var/www/html/index.html

Testing for existence would have probably worked.

Still watching to make sure no other issues come up

**Comment by arthurdent75** [comment]
This issue are no longer present in the new release 2.0 that is about to be published.
If you are an HA advanced user and you want to try it as beta tester add this repository:

https://github.com/arthurdent75/SimpleScheduler-BETA
