### ISSUE TITLE
MQTT switches not created

### ISSUE THREAD

**Issue by Gio-dot** [arthurdent75/SimpleScheduler#105]
Hi, i noticed that mqtt switches where not created even if it seems that Simplescheduler talk with broker. WHat can i check to investigate about the reason?

![2022-12-14 01_38_23-Home Assistant - Scheduler – Home Assistant](https://user-images.githubusercontent.com/55327160/207811344-6d19df25-12a5-4b38-916a-25fdc54cb96e.png)
![2022-12-14 01_39_09-Home Assistant](https://user-images.githubusercontent.com/55327160/207811435-24e61da4-fe13-4fa7-b906-de43a030d378.png)
![2022-12-14 01_40_17-Home Assistant](https://user-images.githubusercontent.com/55327160/207811459-91e64b7f-560a-4d0c-8657-a1d45a4fa101.png)
![2022-12-14 01_41_02-Home Assistant - PC – Home Assistant](https://user-images.githubusercontent.com/55327160/207811511-3e352556-dbb8-4887-a766-efbb31f8ce15.png)

**Comment by arthurdent75** [comment]
This issue are no longer present in the new release 2.0 that is about to be published.
If you are an HA advanced user and you want to try it as beta tester add this repository:

https://github.com/arthurdent75/SimpleScheduler-BETA
