### ISSUE TITLE
Bad Gateway 502 > Permission

### ISSUE THREAD

**Issue by KNXBroker** [arthurdent75/SimpleScheduler#107]
Just installed 2.0.45 on two latest home assistant systems.

Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

I'm not able to get simple scheduler running. Seems to be a permission issue? 
Thank you for your work!

```
[19:57:34] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
[19:57:34] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[19:57:34] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[19:57:34] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
```

**Comment by nico39570** [comment]
Hello
I have the same problem.
I just updated the addon and I can't open it.
Error 502 Bad Gateway

 Add-on version: 2.0.45
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2022.12.1

```
[cont-init.d]` 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:40:42] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
[20:40:42] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[20:40:42] WARNING: example 2 crashed, halting add-on
[20:40:42] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[20:40:43] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[20:40:43] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
[20:40:43] WARNING: example 2 crashed, halting add-on
[20:40:43] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[20:40:44] INFO: Starting service.d [Scheduler]
[20:40:44] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
./run: line 10: /simplescheduler/interface.sh: Permission denied
```

**Comment by svenlange2** [comment]
Same here. Bad gateway. Is there any way to get back to last version ?

**Comment by KoenVanduffel** [comment]
same here too after updating:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 2.0.45
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:02:24] INFO: Starting service.d [Scheduler]
[21:02:24] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[21:02:24] WARNING: example 2 crashed, halting add-on
[21:02:24] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[21:02:25] INFO: Starting service.d [Interface]
[21:02:25] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/interface.sh: Permission denied
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[21:02:25] WARNING: example 2 crashed, halting add-on
[21:02:25] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[21:02:26] INFO: Starting service.d [Interface]
[21:02:26] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/interface.sh: Permission denied
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[21:02:26] WARNING: example 2 crashed, halting add-on
[21:02:26] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory```

**Comment by nico39570** [comment]
> Pareil ici. Mauvaise passerelle. Y a-t-il un moyen de revenir à la dernière version ?

Yes you can easily restore the last backup, provided you have checked "backup" when updating the addon.

**Comment by svenlange2** [comment]
Thank you ! Got 0.65 back. Lets see how it develops here...

**Comment by KoenVanduffel** [comment]
For some reason reverting to 0.65 didn't solve the error. There might however be more going on in my case as I moved from an rPi to a Proxmox virtualized setup today.
Anyway there are only a couple of light schedules in my case so I can easily be patient :).

**Comment by nico39570** [comment]
> Pour une raison quelconque, revenir à 0,65 n'a pas résolu l'erreur. Il se peut cependant qu'il se passe plus de choses dans mon cas, car je suis passé d'un rPi à une configuration virtualisée Proxmox aujourd'hui. Quoi qu'il en soit, il n'y a que quelques horaires légers dans mon cas, donc je peux facilement être patient :).

I had the same thing after the restoration.
Try deactivating and reactivating the addon.
If it doesn't work, try Home Assistant again.

**Comment by KoenVanduffel** [comment]
I am not sure what you mean by deactivating and reactivating (stop-start did not change anything). Also after a reboot I still get the same error (hence back on version 0.65):
```[21:38:32] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
[21:38:32] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[21:38:32] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[21:38:32] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[21:38:33] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
[21:38:33] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[21:38:33] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[21:38:33] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory```

**Comment by jrousek** [comment]
Same here. Bad gateway.

**Comment by aunruh26** [comment]
Hi.

Just updatet to latest Version 2.0.46, sorry to say that but the Problem still remaining.....

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 2.0.46
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.1.1
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:32:11] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[22:32:11] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
[22:32:11] WARNING: example 2 crashed, halting add-on
[22:32:11] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[22:32:12] INFO: Starting service.d [Interface]
./run: line 10: /simplescheduler/interface.sh: Permission denied
[22:32:12] INFO: Starting service.d [Scheduler]
./run: line 10: /simplescheduler/scheduler.sh: Permission denied
[22:32:12] WARNING: example 2 crashed, halting add-on
[22:32:12] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory

**Comment by arthurdent75** [comment]
Sorry guys. Some files lose the x flag during the copy from the beta to the main repository.
Fixed in 2.0.47

**Comment by jrousek** [comment]
I confirm the functionality of version 2.0.47

**Comment by nico39570** [comment]
> Désolé les gars. Certains fichiers perdent le drapeau x lors de la copie de la version bêta vers le référentiel principal. Corrigé dans 2.0.47

Thanks Arthur, I confirm that it works now :-)

```
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:21:59] INFO: Starting service.d [Interface]
[23:21:59] INFO: Starting service.d [Scheduler]
[23:21:59] INFO: Running interface.sh
[23:21:59] INFO: Running scheduler.sh
```

**Comment by KoenVanduffel** [comment]
Great work! It's back up and running.

**Comment by aunruh26** [comment]
Hi.
2.0.47 is working for me too, many thanks. Good Job.

**Comment by KNXBroker** [comment]
Hmmm... Not yet fine for me. Now I have an internal Server error. Logs are fine. Reinstalled, same issue....

**Comment by arthurdent75** [comment]
> Not yet fine for me. Now I have an internal Server error.

Try to restart the addon a couple of times (not reinstall)

If the problem persists, open a new issue. This one is solved. Thanks
