### ISSUE TITLE
Scheduler not working version 2.0.47

### ISSUE THREAD

**Issue by Rudi1952** [arthurdent75/SimpleScheduler#108]
I installed 2.0.47 on two latest home assistant systems.

Home Assistant 2023.1.2
Supervisor 2022.12.1
Frontend-versie: 20230104.0 - latest

After installation logs are ok, but i can't open it. System comes with the following error:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I restarted several times, without any luck.

Logs:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 2.0.47
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2023.1.2
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:40:47] INFO: Starting service.d [Scheduler]
[07:40:47] INFO: Starting service.d [Interface]
[07:40:48] INFO: Running scheduler.sh
[07:40:48] INFO: Running interface.sh

**Comment by arthurdent75** [comment]
try to delete the _option.dat_ file from the folder that stores the JSON files

**Comment by Rudi1952** [comment]
Removed the 'options.dat' file in /usr/share/hassio/share/simplescheduler#
Result is the same:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Stop and start is ok, no problems seen in the log.
Restart however gives the following error:

Restart of the add-on failed
Can't create container from addon_00185a40_simplescheduler: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_00185a40_simplescheduler: Conflict ("Conflict. The container name "/addon_00185a40_simplescheduler" is already in use by container "5f55f96c20f74ab047590d9b1d30b0bbcdf5542f769f52e87a2fd77342563fa2". You have to remove (or rename) that container to be able to reuse that name.")

Removing has no effect, docker container automatically starts again with the same error

**Comment by arthurdent75** [comment]
Why did you close the issue?

**Comment by Rudi1952** [comment]
sorry, mistake

**Comment by arthurdent75** [comment]
It is possible that you have the version from the beta repository still installed?

**Comment by Rudi1952** [comment]
I have version 2.0.47 installed, how can i see if this is the beta version?

**Comment by arthurdent75** [comment]
Your question is already an answer... 
The only suggestion is to uninstall the addon, reboot the Raspberry (not just HA) and then try to reinstall.
I think that something in docker get stuck,,,

**Comment by Rudi1952** [comment]
Uninstalled the addon.
Rebooted the raspberry
Reinstalled the add-on, result: still the same issue...
Uninstalled the addon again. Found out that the directory /usr/share/hassio/share/simplescheduler still existed.
Moved that directory to /usr/share/hassio/share/simplescheduler.old
Rebooted and reinstalled the addon again:

Result: 
502: Bad Gateway

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 2.0.47
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2023.1.2
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:42:46] INFO: Starting service.d [Scheduler]
[18:42:46] INFO: Starting service.d [Interface]
[18:42:46] INFO: Running scheduler.sh
[18:42:46] INFO: Running interface.sh
[2023-01-09 18:42:48] STATUS: Starting main program
Traceback (most recent call last):
  File "/simplescheduler/main.py", line 783, in <module>
    printlog('STATUS: Starting main program')
  File "/simplescheduler/main.py", line 749, in printlog
    with open(logfilepath, "a", encoding='utf-8') as logfile:
FileNotFoundError: [Errno 2] No such file or directory: '/share/simplescheduler/simplescheduler.log'
Traceback (most recent call last):
  File "/simplescheduler/scheduler.py", line 13, in <module>
    main.printlog('STATUS: Starting scheduler')
  File "/simplescheduler/main.py", line 749, in printlog
[2023-01-09 18:42:48] STATUS: Starting scheduler
    with open(logfilepath, "a", encoding='utf-8') as logfile:
FileNotFoundError: [Errno 2] No such file or directory: '/share/simplescheduler/simplescheduler.log'
[18:42:48] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[18:42:48] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory

**Comment by arthurdent75** [comment]
After you rename the folder it can find the log file and crash.
To workaround this you have to manually create an empty _simplescheduler.log_
Meanwhile, I will fix this ASAP

**Comment by Rudi1952** [comment]
Now the situation is;
In the previous JSON directory i now have only one file: /usr/share/hassio/share/simplescheduler/simplescheduler.log
Scheduler works now, thanks very much for your support.
I think i can close this issue now.

**Comment by arthurdent75** [comment]
Thank you for your help!
Closing!
