### ISSUE TITLE
Allow for Swedish Chars in translation

### ISSUE THREAD

**Issue by mcfrojd** [arthurdent75/SimpleScheduler#11]
When i use a Swedish Charter (åäöÅÄÖ) in the settings "translations:"
I get a symbol with a ? inside in the GUI.
If i do text_monday: Måndag
i get a circle with M? for monday.

https://i.imgur.com/eSrHF6H.jpg

On text_ON: Slå på
it seems to work

**Comment by arthurdent75** [comment]
Fixed in 0.21!
