### ISSUE TITLE
"Internal Server Error" if entity is null

### ISSUE THREAD

**Issue by comet424** [arthurdent75/SimpleScheduler#110]
hi i just upgraded to the newest version of scheduler as it came out today.. but that error is back
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

i think its cuz maybe one of the schedules has a no longer entity but i not sure...  how do i downgrade as i forget how to downgrade 

but i going to test if its still the last schedule in my list is the issue

**Comment by comet424** [comment]
ok ya error is back when entiy is null
```{"id":"62685702994be","name":"Grow Light 3","enabled":0,"entity_id":null,"on_tod":"19:00","on_dow":"1234567","off_tod":"13:00","off_dow":"1234567"}```

so i going to edit it manually and copy a entity from another schedule so i can keep this schedule in the list

**Comment by arthurdent75** [comment]
There is a check, indeed. You can safely remove any entity from a scheduler and it won't crash.
If you remove all the entities from a scheduler in the frontend, it will put an empty string as _entity_id_ in the json file.
I have no idea how you get the "null" there. Are you able to describe the steps to replicate the issue?
BTW, I will add this further check.

**Comment by comet424** [comment]
the way i did it  with the older scheduler you had
my steps were i disable the scheduler   but i dont delete them

and i re used the plug, so i deleted it from the settings --> devices & Services and re added it when i re labled it.. so the entity gets erased from there.. i guess at that point your program sees null since its completely removed from devices section

your .64 was it you had me re downgrade to  that fixed that problem when i mentioned it last time and you said  the beta didnt work  2.0  and you had me downgrade with your older version that didnt care about the null

________________________________

**Comment by arthurdent75** [comment]
Fixed in 2.0.50
