### ISSUE TITLE
HVAC Start on first operate mode

### ISSUE THREAD

**Issue by villar3** [arthurdent75/SimpleScheduler#113]
Hi,

when i start my Panasonic HVac with the schedule, the operating mode is the first choice on the comboBox. 

When i stop my Hvac i use the heating mode ("chaud" in french) and when i start i see an other operating mode ("chaud/froid" in french). see the screenshot.

it's possible to set the operating mode with the Scheduler ? like cooler or heating mode.

Thanks

![Capture d’écran 2023-01-18 à 22 41 24](https://user-images.githubusercontent.com/62641534/213301103-253a1e01-7538-442c-8687-168d0abb376a.png)

”’

**Comment by arthurdent75** [comment]
It would be tricky to include such a feature.
Nonetheless, I will keep this in mind as a future improvement
As a workaround, you could create a script to turn on the climate and then call the script from the addon.

Hope you enjoy all the other features!
