### ISSUE TITLE
Add ability to change percentages incrementally

### ISSUE THREAD

**Issue by Malkierian** [arthurdent75/SimpleScheduler#115]
I wasn't really sure how to title this, I don't think that covers it very well. Anyway, I have a dimmable light switch that I have setup in HA automations currently to run a certain number of times and increase the percentage by 10% each time. I think I know how I can do it with what you have now, but to be able to put in `8:00+B10 8:01+B10` instead of having to put in each specific percentage each time (I had it set up to do 20 times because sometimes HA would fail to trigger it even though it thought it did. Don't know if Scheduler has this problem also). Shorthand for recurrence would be nice, too, but can also be worked around.

**Comment by Malkierian** [comment]
I also just realized that, since I increment it off at night as well, but the brightness modifier doesn't work in the OFF box, that I'll have to have all of the things in the ON box, and it's very hard to navigate all those entries in a small line, so having that as a textbox with text wrapping instead of a text field with overflow hidden would be really nice.

**Comment by arthurdent75** [comment]
Thank you for your suggestion.
Anyway, I think this is not the more efficient way to achieve this. 
I have a similar need: I have a sequence of events with some pauses in between.
I've just created a script, and I run the script from the Addon at the first occurrence of the sequence. The script does the rest.

**Comment by Malkierian** [comment]
You know, that's actually a fair point, I'd forgotten scripts were an option here. It ends up being roundabout, since a script is just one step away from an automation, but it does still allow for time management using your program. I'll do it that way, thanks. And I just realized you can do Choose actions in scripts so that you can combine on and off functionality into one script that your app runs, which is absolutely fantastic. The way your app handles that is a lot better than the way HA would handle it.

It would be nice, though, if you could somehow link a script entry in your app to the editor for that script, but would be a minor convenience improvement.

**Comment by arthurdent75** [comment]
> It would be nice, though, if you could somehow link a script entry in your app to the editor for that script, but would be a minor convenience improvement.

Sadly this is not possible, because the addons (any, not just mine) are "external" websites that look integrated into the same dashboard, but in reality, are completely detached from HA. So I cannot recall the script editor in a neat way. Sorry.

Anyway, I'm glad you enjoy my addon.
