### ISSUE TITLE
Move "Enabled" to a button on the main page

### ISSUE THREAD

**Issue by Malkierian** [arthurdent75/SimpleScheduler#116]
I think it would make things easier to have an instant save toggle on a schedule's row, probably next to the edit button or something, that would enable or disable the schedule instead of having to pull up the edit menu just to hit a checkbox. Was honestly surprised that HA's automations didn't have an easily accessible toggle, either.

**Comment by arthurdent75** [comment]
In the very first release of the addon, the switch was there. 
I mainly use the app from the phone. 
I realize that I could disable a schedule by mistake while scrolling the list. 
That’s why I decide that if I want to disable a schedule, I have to edit it.
