### ISSUE TITLE
Feature: first/last of sunset/sunrise and time

### ISSUE THREAD

**Issue by micw** [arthurdent75/SimpleScheduler#117]
Hello,

I'm opening my blinds a while sunrise which works pretty well with "sunrise+30". A problem is that the sun will rise very early in summer. Would it be possible to say "sunset or 07:00, whatever comes last"?

Considerations:
* use cases with first/last exists for both time+sunset and time+sunrise. so the expression for it needs to specify which one to use. could be done by different keywords like `sunrise_not_before+60,08:00` or `sunrise_not_after+60,08:00` or by kind of expression `first(sunrise+60,08:00)` - the later ist better to read but slightly more complex to parse
* the time of sunset/sunrise must be calculated for the current day, not for the current timestamp. otherwise, the expression `first(sunrise+60,08:00)` would return "08:00" if sunrise is before 08:00 and the expression is evaluated with a time between sunrise and 08:00

**Comment by arthurdent75** [comment]
This is very tricky.
I think that automations will fit best in your scenario.
