### ISSUE TITLE
File with automations

### ISSUE THREAD

**Issue by TeleporterGuy** [arthurdent75/SimpleScheduler#118]
Hi,
i previously had some issues with Simple Scheduler, but they were eventually solved. Some scheduled automations got lost (were no longer visible after reinstalling Simple Scheduler). But I have a suspicion the scheduler is still triggering it. Some unknown source is triggering one automation at 7.00 (this was previously set in Simple Scheduler). Checking the HA log files, i only see the action was performed, but I can't see trigger.
Could you please navigate me to file, which stores the user defined scheduled actions?

Thanks, BR

**Comment by arthurdent75** [comment]
> Could you please navigate me to file, which stores the user-defined scheduled actions?

The schedulers are JSON files.
They are stored under the **/share/simplescheduler** folder.
You can reach them in many ways: the most common one is through the SAMBA share.
You can open it with a text editor and figure out which one is executed but not shown. Then you can safely remove it.
It would be useful if you could send me this JSON file before you delete it, so I can understand why it is hidden in the frontend. This would help me to identify the bug.

**Comment by TeleporterGuy** [comment]
Thanks for support.
Good news, only the visible schedules are present in json file. No bug is present.
Bad news for me. I have to keep on searching, what triggers the movement of one of my covers daily at the same time.
