### ISSUE TITLE
Sensor "Simple Scheduler Running" does not update

### ISSUE THREAD

**Issue by Jottlas** [arthurdent75/SimpleScheduler#119]
I activated the sensor "Simple Scheduler Running" in the Simple Scheduler device, but the sensor does not seem to update properly when I am starting and stopping the addon.

**Comment by arthurdent75** [comment]
This is a feature of the HA Supervisor. It is not something that I somehow manage with the addon.
Please, check if you have the same issue with other add-ons.

**Comment by Jottlas** [comment]
Seem to be correct. I did the same setup with the Let's encrypt add-on and it has the same issue.
Thanks for your consideration! (and for the plugin!!)
