### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by frankiha** [arthurdent75/SimpleScheduler#12]
currently running version 0.108.6

Warning: file_put_contents(/share/simplescheduler/sun.dat): failed to open stream: Permission denied in /var/www/html/lib.php on line 234

**Comment by arthurdent75** [comment]
Try to reinstall it

**Comment by frankiha** [comment]
hi Arthur
LOG
i Apr 24 10:47:01.046984 2020] [mpm_prefork:notice] [pid 11] AH00163: Apache/2.4.38 (Debian) PHP/7.3.17 configured -- resuming normal operations
[Fri Apr 24 10:47:01.049733 2020] [core:notice] [pid 11] AH00094: Command line: 'apache2 -D FOREGROUND'

Warning: file_put_contents(/share/simplescheduler/sun.dat): failed to open stream: Permission denied in /var/www/html/lib.php on line 234

Warning: file_put_contents(/share/simplescheduler/sun.dat): failed to open stream: Permission denied in /var/www/html/lib.php on line 234

Warning: filemtime(): stat failed for /share/simplescheduler/sun.dat in /var/www/html/lib.php on line 208

Warning: file_put_contents(/share/simplescheduler/sun.dat): failed to open stream: Permission denied in /var/www/html/lib.php on line 234

Warning: file_get_contents(/share/simplescheduler/sun.dat): failed to open stream: Permission denied in /var/www/html/lib.php on line 210

Notice: Trying to get property 'next_setting' of non-object in /var/www/html/lib.php on line 211

Notice: Trying to get property 'next_rising' of non-object in /var/www/html/lib.php on line 212

CONTAINER
root@00185a40-simplescheduler:/var/www/html# ls -lha
total 44K
drwxrwxrwx 1 www-data www-data 4.0K Apr 24 10:59 .
drwxr-xr-x 1 root     root     4.0K Apr 23 13:34 ..
-rwxr-xr-x 1 root     root      250 Apr 17 13:19 conf.php
-rwxr-xr-x 1 root     root     8.4K Apr 17 13:19 index.php
-rwxr-xr-x 1 root     root     7.0K Apr 17 13:19 lib.php
-rwxr-xr-x 1 root     root     1.2K Apr 17 13:19 scheduler.php
-rwxr-xr-x 1 root     root     1.5K Apr 17 13:19 script.js
-rwxr-xr-x 1 root     root     1.6K Apr 17 13:19 style.css
root@00185a40-simplescheduler:/var/www/html#

FOLDER
\share\simplescheduler
scheduler.log
sun,dat

thanks
Frank

**Comment by arthurdent75** [comment]
The file sun.dat is there. There is no apparent reason why you get a "permission denied" error.
Also, sun.dat is not copied by the setup, but is generated on the first execution, so it was able to write it in the first place.
