### ISSUE TITLE
Some warning entries in Supervisor log

### ISSUE THREAD

**Issue by dragonjon** [arthurdent75/SimpleScheduler#121]
Thanks for your work and the new version works great.
Thanks, in advanced
Jon

I look these entries in Supervisor log, is correct?

23-02-16 10:30:31 WARNING (MainThread) [supervisor.addons.options] Option 'translations' does not exist in the schema for Simple Scheduler (00185a40_simplescheduler)
23-02-16 10:30:31 WARNING (MainThread) [supervisor.addons.options] Option 'components' does not exist in the schema for Simple Scheduler (00185a40_simplescheduler)
23-02-16 10:30:31 WARNING (MainThread) [supervisor.addons.options] Option 'MQTT' does not exist in the schema for Simple Scheduler (00185a40_simplescheduler)
23-02-16 10:30:31 WARNING (MainThread) [supervisor.addons.options] Option 'max_retry' does not exist in the schema for Simple Scheduler (00185a40_simplescheduler)
23-02-16 10:30:31 WARNING (MainThread) [supervisor.addons.options] Option 'details_uncovered' does not exist in the schema for Simple Scheduler (00185a40_simplescheduler)
23-02-16 10:30:31 WARNING (MainThread) [supervisor.addons.options] Option 'dark_theme' does not exist in the schema for Simple Scheduler (00185a40_simplescheduler)
23-02-16 10:30:31 WARNING (MainThread) [supervisor.addons.options] Option 'debug' does not exist in the schema for Simple Scheduler (00185a40_simplescheduler)

**Comment by arthurdent75** [comment]
> I look these entries in Supervisor log, is correct?

No, it is not.

The options have been moved inside the addon.
Your supervisor somehow "remembers" that the addon had options (maybe some cache mechanism) but it is not able to find them anymore.
If I have a guess, I think that rebooting your Home Assistant PC (or raspberry or whatever) could clean the cache and remove the warning.

Let me know if it solves this.

**Comment by dragonjon** [comment]
I resolve the enigma
with images better.....
![Captura de pantalla 2023-02-16 220132](https://user-images.githubusercontent.com/15904661/219487800-fe29a96d-84df-44b7-9fbb-73e90bcc599f.png)
![Captura de pantalla 2023-02-16 220205](https://user-images.githubusercontent.com/15904661/219487806-be9b5634-85fb-4951-816e-0a1158e624e9.png)
![Captura de pantalla 2023-02-16 220624](https://user-images.githubusercontent.com/15904661/219487809-9dafcbba-a034-4a5b-8e9f-b3a2b5d8a61b.png)

Wen deletes all the info in yaml file in the config and save and restart de Simple Scheduler all is gone, included the config page.

Thanks for your time, effort and great work.
Jon

**Comment by arthurdent75** [comment]
Thank you for your investigation.
Glad you solved it!
