### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by sveba** [arthurdent75/SimpleScheduler#126]
Hi,
why don't you offer an official docker image?

**Comment by arthurdent75** [comment]
This is not the first time I got this request.
I'm not such an expert on the Docker universe... 😊 
What would the advantage be?

**Comment by sveba** [comment]
you would skip `git clone` and `docker build` 
Also there are user who use kubernetes or similar. Then you have to build the docker image somewhere and than push it to a repo, and than pull

Repositories and prebuild images are state of the art :)

**Comment by arthurdent75** [comment]
Ok, I will dig into it.

**Comment by rossman-home** [comment]
I looked around and didn't see anything, but any update to this?

**Comment by arthurdent75** [comment]
> I looked around and didn't see anything, but any update to this?

You are right.
I will restart work on the project after the holidays.
Thank you for your patience.

**Comment by arthurdent75** [comment]
I started to make some tests on this...

`docker pull ghcr.io/arthurdent75/simplescheduler:master`

For now, it is built for _amd64_ only. 
I'm trying to add _armhf_ for raspberry 
I hope it will be ready soon...

**Comment by arthurdent75** [comment]
Better late than never 😅 
Done!
