### ISSUE TITLE
Addon does not start - "example 2 crashed, halting add-on"

### ISSUE THREAD

**Issue by amrit-venkatesh** [arthurdent75/SimpleScheduler#128]
My first ever issue submission on GitHub, apologies if there are expected additions/information that I've missed so please let me know. I'm facing the following error when running this addon on a new installation of Home Assistant. 

The addon installs successfully but does not start. 
Clicking WebUI button gives a blank screen with this error: "502: Bad Gateway"
Selecting the Configuration tab gives this message: "This add-on has no configuration."

Logs:

````
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 2.11
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.5.1
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:30:44] INFO: Starting service.d [Scheduler]
[18:30:44] INFO: Starting service.d [Interface]
[18:30:44] INFO: Running scheduler.sh
[18:30:44] INFO: Running interface.sh
[2023-05-06 18:30:45] STATUS: Starting main program
Traceback (most recent call last):
  File "/simplescheduler/main.py", line 793, in <module>
    if options['MQTT']['enabled']:
KeyError: 'MQTT'
[18:30:48] WARNING: example 2 crashed, halting add-on
./finish: line 7: /run/s6/basedir/bin/halt: No such file or directory
[18:30:48] INFO: Starting service.d [Interface]
[18:30:48] INFO: Running interface.sh
[2023-05-06 18:30:49] STATUS: Starting main program
Traceback (most recent call last):
  File "/simplescheduler/main.py", line 793, in <module>
    if options['MQTT']['enabled']:
KeyError: 'MQTT'`

The lines from "WARNING: example 2 crashed..." to "KeyError: 'MQTT'" repeats indefinitely. 

Have attempted restarting and rebuilding the addon to no avail.

**Comment by amrit-venkatesh** [comment]
What's really strange is I have another instance of Home assistant on which I've been using this scheduler for ages and where I just updated it from v0.3 to v2.11 and it works fine. I'm not python/mqtt savvy enough to figure out what the error on this instance means though. Would appreciate any help I can get.

**Comment by amrit-venkatesh** [comment]
I have another instance of Home Assistant where I've been using your addon for years and where I just updated from v0.3 to 2.11 and I'm facing the same issue there too.

**Comment by arthurdent75** [comment]
Have you tried restarting the whole Home Assistant?

**Comment by arthurdent75** [comment]
Try this:

1. backup the _/share/simplescheduler_ folder somewhere on your PC
2. uninstall the addon
3. delete all the files from the folder (you can leave the empty folder)
4. install the addon and start it

Verify if you are able to open the front end. Should be empty. That's normal.

If the frontend loads, you can restore the schedulers: 
copy **ONLY the JSON files** from the backup to the _/share/simplescheduler_ folder and restart the addon.

**Comment by amrit-venkatesh** [comment]
Worked like a charm! Thank you so much! I was wondering how one can go about reinstalling the addon without losing existing schedules and this is it. 

Just one question though. The 'Configuration' tab of this addon is still empty with a message - "This add-on has no configuration". Is that normal? I recall the old v0.3 had definitions for days of the week or thereabouts.
