### ISSUE TITLE
Power Outages

### ISSUE THREAD

**Issue by sugarfunk** [arthurdent75/SimpleScheduler#132]
I learned the hard way today that if power flickers and the bulb state is lost ( in my case a heat lamp light that must be on for dragon) the  state won’t resume. 

Long shot here, but any chance to poll on some set time to ensure switch/lights are in their correct states during a given schedule?

like if it should be on from 800 to 2200, have it poll hourly to ensure on and if not, resume to schedule?

**Comment by arthurdent75** [comment]
This is not how it works.
The scheduler is not designed to FORCE the entity on or off.
It just executes a command at a given time.

This is not an issue and it won't be considered as an improvement 😅
