### ISSUE TITLE
Feature: "Number" domain

### ISSUE THREAD

**Issue by micw** [arthurdent75/SimpleScheduler#133]
Hello,

I'm using and loving this piece of software. Recently I changed my garden water entities from light to number because that fits way better. Would you mind to add support for this domain?

Proposal:
* The action is "set value"
* "unit_of_measurement" should be used from the entity to display the unit
* "device_class" could be used to show an appropriate icon

**Comment by arthurdent75** [comment]
The main working principle is to work on entities that support _turn_on_ and _turn_off_ services.
