### ISSUE TITLE
huge data size

### ISSUE THREAD

**Issue by scooterama** [arthurdent75/SimpleScheduler#137]
my backup file is about 250MB and if I uninstall simple scheduler it's about 40MB.
Unfortunately I can't find the data-folder so when I install it again all data is back and the backup size is again 5x as big. 

I uninstalled it, made a backup (with small size as expected) and now it won't install again. Where's the files to delete so the installation won't access the old data?

**Comment by arthurdent75** [comment]
This is not an issue.
The data are persistent. So if you uninstall the addon, they are still there. Indeed, you are still backing up the data even if the addon is uninstalled.

The real deal is that HA saves in the backup the images of the dockers used by the addons. This happens for all addons.
If you restore a full backup, you will find the same version of the addons you had at the moment of the backup, even if they were updated (or they are not available anymore) in the meantime.

It will seem "huge" to you, but if you install many addons and start having thousands of sensors, it's easy to have such a big backup size.

Just to give you an idea... this is my backup:
![image](https://github.com/arthurdent75/SimpleScheduler/assets/60071192/d3338eef-cee4-4b05-8ad2-8a905818707e)

I hope I make myself clear 😃

**Comment by papperone** [comment]
Just realized this and it seems only this addon is affected by the behaviour described; if HA would behave as explained I would expect all addons to be fairly huge, but belo is one of my latest backup and only simple_scheduler is unexplicably ginormus!
![immagine](https://github.com/user-attachments/assets/57ee9072-6070-48bf-9139-9acdcb8360b6)
MariaDB is correct as this is my main database, but how comes HA itself is less then 25% of simple_scheduler backup???

**Comment by arthurdent75** [comment]
As I said, my addon docker image is stored in the backup. If you open the simplescheduler archive you will see _image.tar_ file that uses all the space.
In many other addons (but not all of them) the image points to a URL because it is stored online, so it is not stored in the backup.
There is nothing I can do at this time.

**Comment by papperone** [comment]
> As I said, my addon docker image is stored in the backup. If you open the simplescheduler archive you will see _image.tar_ file that uses all the space. In many other addons (but not all of them) the image points to a URL because it is stored online, so it is not stored in the backup. There is nothing I can do at this time.

thanks for the fast reply, I mean I can understand but I think it's a bit illogical to carry on 500Mb of docker image in my backup for just an addon, imagine all will follow this practice all backup files will be few dozens of Gigabytes!!!!
