### ISSUE TITLE
[Feature Request] add parameters for RGB/CT lights

### ISSUE THREAD

**Issue by papperone** [arthurdent75/SimpleScheduler#138]
Currently you can setup only the brightness of a light, it woudl be great to add as well possibility to schedule a light to turn on at a specific color (RGB) or temperature (CT)

**Comment by arthurdent75** [comment]
![image](https://github.com/arthurdent75/SimpleScheduler/assets/60071192/a9b0864a-c3e4-441a-939e-ca3e0bf6d5ac)
The new feature is on its way...
