### ISSUE TITLE
Backup size increased by 4x

### ISSUE THREAD

**Issue by scooterama** [arthurdent75/SimpleScheduler#139]
My full backup of hassio went from 70MB to 240MB just with simple scheduler installed or without. 
I tried deleting all schedules, "build new" and unistall/install, but as far as I've seen it restores my data anyways.

**Comment by bilogic** [comment]
@arthurdent75

Possible to point your `config.yaml` to a docker image instead to fix this?

**Comment by arthurdent75** [comment]
As discussed here #85 #137 and multiple times on the forum (https://community.home-assistant.io/t/simple-scheduler-addon/174326) this is not an issue. It is normal behavior.

I think that @bilogic gets the point as an improvement.
So follow #126
