### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by coolduke666** [arthurdent75/SimpleScheduler#14]
hi, great work. really love the idea... 

two questions: 
a) does eg "sunset" work like in standard automations? addional an offset would be great!
b) having a defined ON time (eg 60 mins) would be nice, instead of an defined OFF time. eg: switch light on at "sundown-1" and leave the light on for 60 mins
c) adding some conditions would also be great, eg very simple a list of available input_booleans would be enough, because you can set these booleans in other scripts/automations.

great work!
 

are there any further improvements planned?

**Comment by arthurdent75** [comment]
Thanks for your suggestions
