### ISSUE TITLE
Feature request write values to helpers

### ISSUE THREAD

**Issue by HMvdZijden** [arthurdent75/SimpleScheduler#140]
It would be nice when values of helpers could be set bij the scheduler.
The most wanted for me would be the input_number.
It can be done by scripts, but than you need scripts and schedule entries for every value.

**Comment by sleveille4** [comment]
i second that, i do use a TPI script to have a better thermostat than what is actually offered by the climate entities, and i "just" need to change the value of an input_numer on a schedule.

**Comment by arthurdent75** [comment]
If the entities cannot manage turn_on or turn_off services, cannot be addressed.
Sorry, can't do that.
