### ISSUE TITLE
Simple Scheduler no longer switching on lamps with brightness

### ISSUE THREAD

**Issue by bjornekelund** [arthurdent75/SimpleScheduler#142]
I have a Zigbee lamp "AduroSmart Eria" and it has worked well with Simple Scheduler but since a 
few days (which may coincide with the new Home Assistant release) it no longer switches on when 
I use "17:35>B35" commands. It only switches on with "17:35". Switching off is, of course, no problem. 
Controlling the lamp from a script using the lamp:start service works just fine.

**Comment by arthurdent75** [comment]
You are right.
Fixing it asap
