### ISSUE TITLE
[feature request] Sunset and Rise time display

### ISSUE THREAD

**Issue by tannibanani** [arthurdent75/SimpleScheduler#144]
It would be really neat if the sunset and rise time was displayed in the gui. The time that is used by the addon.

i’ve spent too much time trouble shooting why an action wasn’t run when I used sunset+/- offset before realizing I had the wrong sunset and rise time.

**Comment by arthurdent75** [comment]
Always been there!

![image](https://github.com/arthurdent75/SimpleScheduler/assets/60071192/eeade6d6-124a-42c6-80f7-b93a34fe18dc)
