### ISSUE TITLE
Retry on unavailable  By default, SimpleScheduler will retry 3 times if an entity is unavailable.

### ISSUE THREAD

**Issue by davlaw** [arthurdent75/SimpleScheduler#145]
I had mine set to a rather high number, 35.  But it seems to only offer 5 checks and gave up.

Guess my question is what are valid entries for "retry"

**Comment by arthurdent75** [comment]
You are right. It is not written anywhere. Five times is the maximum 
![image](https://github.com/arthurdent75/SimpleScheduler/assets/60071192/cf04676a-cdfd-4d68-aa4a-5c2fbef9ade1)
I will update the documentation.
