### ISSUE TITLE
Valve available

### ISSUE THREAD

**Issue by Kaibob2** [arthurdent75/SimpleScheduler#146]
Hi there, as of HA Core 2024.1.0 there is an option to define switches as valves. Will there be the possibility to have valves in Simple Scheduler?

**Comment by arthurdent75** [comment]
I will add this feature in the next beta

**Comment by arthurdent75** [comment]
@Kaibob2 the valve is now available in the beta version.
More info on how to use beta:
https://community.home-assistant.io/t/simple-scheduler-addon/174326/440?u=arthurdent1975

**Comment by Kaibob2** [comment]
Great, thanks, but where is 2.5?

**Comment by arthurdent75** [comment]
My bad. I published the new version without changing the config file with the new release number. Try again now.
