### ISSUE TITLE
Enhancement Request: Enable TLS Certificate Authentication for Enhanced Security in Connection Establishment

### ISSUE THREAD

**Issue by h-theLetter** [arthurdent75/SimpleScheduler#150]
To further enhance security in connection establishment, I propose the implementation of TLS certificate authentication. This would add an extra layer of validation, ensuring secure communication between clients and the server.

Proposed Changes

**TLS Certificate Validation:**
Introduce the ability to validate TLS certificates during the connection establishment process. This ensures that only authorized clients with valid certificates can connect.

**Specify Certificate, Key, and CA Location:**
Allow users to specify the location of client certificates, private keys, and the Certificate Authority (CA) files. This could be achieved by adding a configuration option, and the default location could be set to the SSL directory.

Configuration Example (if applicable)
```
tls:
  enabled: true
  certificate:
    path: client.crt
  key:
    path: client.key
  ca:
    path: ca.crt
```

I appreciate the incredible work done on this project so far and appreciate any extra effort!

**Comment by arthurdent75** [comment]
Hi @h-theLetter, thank you for your support and your suggestion.
I'm not sure about the advantages of your proposal.
If you publish HA on HTTPS and you choose _show in sidebar_, SimpleScheduler is proxied (like any other addon) and thus is also in HTTPS.
The only insecure communication is between HA and the addon, but they run on the same computer, so it is very unlikely that someone could steal packets in the middle.

Please let me know your thoughts!

**Comment by h-theLetter** [comment]
Hi there, the scenario I was thinking of if when you are running an external MQTT broker and not the add-on from HA (Which I am, but requires certs so am not using with SimpleScheduler). However now that I'm thinking about it, you would also have to add configs to point to the broker. It's a big undertaking so maybe just something to keep in mind down the road. Either way, thank you!

**Comment by arthurdent75** [comment]
> you would also have to add configs to point to the broker. It's a big undertaking so maybe just something to keep in mind down the road.

It is already there:
![image](https://github.com/arthurdent75/SimpleScheduler/assets/60071192/1fff8d1f-6e5c-4c87-acca-ebc782edf2ee)

**Comment by h-theLetter** [comment]
Perfect! I didn't realize you could enter an external server there. So that would be the benefit if you added this enhancement 😊 Allowing users to connect to external servers that require certificates.

**Comment by arthurdent75** [comment]
Don't get me wrong... I think there is too much effort compared to the number of users that could use this.
I believe that the majority of users point to Home Assistant Mosquitto Addon...
Thank you anyway for your suggestion and for using my addon!
