### ISSUE TITLE
Question: Delete the log?

### ISSUE THREAD

**Issue by Joo01** [arthurdent75/SimpleScheduler#152]
First of all, thank you for the easy and well running addon!

But how do I delete the log entries, respectively the whole log of the SimpleScheduler which are created during the runtime?
Unfortunately I can't find this in the description or see a button for it.

Best Regards

**Comment by arthurdent75** [comment]
You are right.
I wrote it many times while helping other users, but there is no trace of it in the documentation.
The log file is stored in the [share/simplescheduler] folder, along with the JSON files of the schedulers.

I will update the docs in the next release.
Thank you

**Comment by arthurdent75** [comment]
Fixed in 2.5
