### ISSUE TITLE
Is there any way to call a particular schedule as a service?

### ISSUE THREAD

**Issue by danielrosehill** [arthurdent75/SimpleScheduler#154]
Hey!

Very useful tool!

A quick question.

I'd like to display the current schedule for a particular item on a dashboard I'm building. 

There's no way to do that currently, right (as in... the individual scheduling entities aren't pollable)?

**Comment by arthurdent75** [comment]
Sorry, I'm not sure about what you mean.

"_Is there any way to call a particular schedule as a service?_" 
I would tell you that there is a misconception... you should wrap all the action into a script, then call the script from the scheduler.

"_I'd like to display the current schedule for a particular item on a dashboard_"
Not sure about what you want to see on your dashboard. You can enable the MQTT feature and then you have a switch for every scheduler. 

Fill free to express with more details if I didn't answer to your request.
