### ISSUE TITLE
Unable to install Add-in.

### ISSUE THREAD

**Issue by PieterHattinghZA** [arthurdent75/SimpleScheduler#158]
I removed the Add-on to try and resolve an upgrade error, and now when I try to re-install I get the following error

Failed to install Add on

The command '/bin/bash -o pipefail -c apt-get install -y coreutils wget curl python3 python3-dev python3-pip' returned a non-zero code: 100

![image](https://github.com/arthurdent75/SimpleScheduler/assets/87018608/cf456f04-687d-4722-a16d-2cde85733970)

Please asisst or advise

**Comment by arthurdent75** [comment]
I think some docker image still stay in cache.
Try to reboot your device (not home assistant, the full device)

**Comment by PieterHattinghZA** [comment]
> I think some docker image still stay in cache. Try to reboot your device (not home assistant, the full device)

I am running HA in Virtual Box on a laptop. I've restarted the VM, the Host OS, even cleared the Host's history, cache and temp files. Still get the error

**Comment by PieterHattinghZA** [comment]
Issue still not resolved

________________________________

**Comment by arthurdent75** [comment]
> Issue still not resolved

Sorry, I didn't receive an answer to my question for a month so I thought it was solved.

I also use VirtualBox for testing the addon, including updates and fresh installs.
I was unable to recreate the issue on a fresh install.

**Comment by PieterHattinghZA** [comment]
I had the integration running previously with no issues, until there was an update.

The update produced an error, and I tried to uninstall the integration, to re-install it.

Since then I have not been able to get it working.

Could you maybe indicate in what location I can manually remove any orphaned remnants of the integration, to attempt to then try and re-install it


This e-mail and any attachments thereto are strictly confidential and are intended solely for the use of the addressee. Should
you not be the intended addressee, please delete this e-mail message immediately. While care is taken in preparing this document, no representation, warranty or undertaking (expressly or implied) is given and no responsibility nor liability is accepted by the company as to the accuracy of the information contained herein, that the email is free of viruses, or for any damages that may occur from receiving or opening this email.

**Comment by dylancollaud** [comment]
I got the same problem with brand new installation HomeAssistant on RPI 5 with OS Homeassistant. 
On other installation same configuration, I didn't get this error.

**Comment by arthurdent75** [comment]
I'm truly sorry but I'm unable to recreate the issue, so I have no clue.
The dockerfile is executed correctly wherever I've tested it, even on github action.

**Comment by PieterHattinghZA** [comment]
I would like to try something else.

What is the location where the files are installed?

I want to manually remove any trace of the program and then install it again.

It is a brilliant add-on that you wrote and I applaud your skill.


[cid:24d6fd47-7a97-44cd-b55b-122d77876332]

This e-mail and any attachments thereto are strictly confidential and are intended solely for the use of the addressee. Should

you not be the intended addressee, please delete this e-mail message immediately. While care is taken in preparing this document, no representation, warranty or undertaking (expressly or implied) is given and no responsibility nor liability is accepted by the company as to the accuracy of the information contained herein, that the email is free of viruses, or for any damages that may occur from receiving or opening this email.



________________________________

**Comment by arthurdent75** [comment]
> What is the location where the files are installed?

Sorry, I have no idea where HA saves the docker images.

**Comment by dylancollaud** [comment]
I look the log of HomeAssistant and I found that : 

`2024-08-29 22:45:08.433 INFO (MainThread) [supervisor.addons.addon] No 00185a40_simplescheduler addon Docker image 00185a40/aarch64-addon-simplescheduler found
2024-08-29 22:45:08.434 INFO (MainThread) [supervisor.docker.addon] Starting build for 00185a40/aarch64-addon-simplescheduler:2.5
2024-08-29 22:45:09.905 ERROR (MainThread) [supervisor.docker.addon] Can't build 00185a40/aarch64-addon-simplescheduler:2.5: The command '/bin/bash -o pipefail -c apt-get install -y     coreutils     wget 	curl 	python3 	python3-dev 	python3-pip' returned a non-zero code: 100
2024-08-29 22:45:09.905 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/13 : ARG BUILD_FROM


Step 2/13 : FROM ${BUILD_FROM}


 ---> 64b146dd73ec

Step 3/13 : RUN apt-get update -y && apt upgrade -y


 ---> Using cache

 ---> b7c6fe233019

Step 4/13 : RUN apt-get install -y     coreutils     wget 	curl 	python3 	python3-dev 	python3-pip


 ---> Running in df0d48441d3a

Reading package lists...


Building dependency tree...

Reading state information...


E: Unable to locate package wget
E: Unable to locate package python3
E: Unable to locate package python3-dev
E: Unable to locate package python3-pip

 ---> Removed intermediate container df0d48441d3a`

Maybe you will see the error behind code error 100. 

Why the system can't locate all package ?

**Comment by dylancollaud** [comment]
If I try to install manualy this components with ha add: 

RUN apt-get install -y \
    coreutils \
    wget \
	curl \
	python3 \
	python3-dev \ 
	python3-pip

The only one who doesn't work is pyhton3-pip, (No such package)

**Comment by arthurdent75** [comment]
@dylancollaud thank you for your investigation.
The error is completely nonsense.
I will try to set up a beta repository with some changes in the dockerfile so that you can run some tests.

**Comment by arthurdent75** [comment]
@dylancollaud could you uninstall the addon, add this addon repository:
https://github.com/arthurdent75/SimpleScheduler-BETA
and try to install 2.5.8b from here?

**Comment by dylancollaud** [comment]
@arthurdent75 
Thank you for this version. **It's work !**

**Comment by arthurdent75** [comment]
Ok, It just downloads the docker image instead of compiling it.
I will add this in the next release.
Until then keep this repository. As soon as a new version comes out, switch back to the official one.
Thank you for the help!

**Comment by dylancollaud** [comment]
Perfect, thank you for having solved this problem.

**Comment by PieterHattinghZA** [comment]
Hi, Worked for me also!!!


[cid:193a7c07-2b87-4634-aac9-f2218736e0c8]

This e-mail and any attachments thereto are strictly confidential and are intended solely for the use of the addressee. Should

you not be the intended addressee, please delete this e-mail message immediately. While care is taken in preparing this document, no representation, warranty or undertaking (expressly or implied) is given and no responsibility nor liability is accepted by the company as to the accuracy of the information contained herein, that the email is free of viruses, or for any damages that may occur from receiving or opening this email.



________________________________
