### ISSUE TITLE
Potential for missed schedule

### ISSUE THREAD

**Issue by hudcap** [arthurdent75/SimpleScheduler#159]
Hi!
First, thank you for this awesome integration!

I was reviewing your code, and if I understand correctly, the code checks every second to see if the current time has zero seconds, and if it does, it checks if any events are scheduled.
Supposed the scheduler starts running with 59.999 seconds. Suppose the sleep plus the call for current time lasts just a drop more than a second (maybe because of a heavy cpu load). Then in the next loop, the current time may have 1.001 seconds, and any scheduled events for that minute will never run.

Am I off my mark here?
If you think this is a concern, I'm happy to discuss alternatives and make a PR.

**Comment by arthurdent75** [comment]
Thank you for your analysis.
What you say is potentially correct. This was a concern of mine, indeed. In the first alphas (never released) I checked the first 5 seconds of the minutes. I realize with some specific tests that the _while_ runs hundreds of times on a raspberry. So I decided to keep only the zero check.
For 4 years, this never happened to me nor did anyone report this.
I believe we could agree that there is no such concern.

**Comment by hudcap** [comment]
Thank you for such a prompt reply!
In the interest of reducing the number of loops, why not sleep until the next zero second, and then skip the zero check?

**Comment by hudcap** [comment]
> take the second at the end of the cycle and sleep for a complementary number of seconds
I think we're saying the same thing. The sleep at the end of the loop would be for (60 minus the current number of seconds).
But I completely understand your position.
Thank you!
