### ISSUE TITLE
Feature request: support generic values

### ISSUE THREAD

**Issue by giggo** [arthurdent75/SimpleScheduler#16]
Hi
how about not just supporting switches, lights etc it would be great to have a component that can output multiple values by time.
e.g. 8.00-9.00 -> 1 (heating program 1)
9.00-10.00 -> 2 (heating proogram 2)
...

**Comment by Alfiegerner** [comment]
Yes please - I came to this looking for scheduling my automower which presents as a vaccuum  in HA.  I want to use HA to schedule a weekly pattern and it's a bit of pain using the native UI.

**Comment by arthurdent75** [comment]
Thanks for your suggestion
