### ISSUE TITLE
[2024-06-24 06:54:05] ERROR: Unable to obtain entities names from Home Assistant

### ISSUE THREAD

**Issue by davlaw** [arthurdent75/SimpleScheduler#160]
Not sure when this might have started, but it is showing up in logs.  I have recently started adding to the scheduler, but have been using it for sometime with a few entries.  Have rebuilt via HA within the add on menu.

What can I add here that might help?

Core 2024.6.4 
Supervisor 2024.06.0 
Frontend 20240610.1

I have just now enabled "debug", will add data as I can

**Comment by arthurdent75** [comment]
If you can create a new scheduler and find the list of the entities, you don't have to worry about that error.
You are surely getting this error in the log while HA is updating or restarting. In this scenario, the add-on is running but cannot contact HA.

**Comment by davlaw** [comment]
I'll go with that
