### ISSUE TITLE
schedule based on Jewish Calendar Add On 

### ISSUE THREAD

**Issue by dovy6** [arthurdent75/SimpleScheduler#164]
Would it be possible to allow building schedules off of the Jewish Calendar integration? The integration creates a bunch of sensors named "sensor.jewish_calendar_[event name]" 

Similarly to how I can now set the lights to go on at "SUNSET-30" and they'll go on 30 minutes before sunset, I'd like to set them to go on "sensor.jewish_calendar_shkia-30" and have them go on 30 minutes before Shkia. Would that be possible to do?

https://www.home-assistant.io/integrations/jewish_calendar/

Thanks very much

**Comment by arthurdent75** [comment]
I don't think this is possibile... sorry...
