### ISSUE TITLE
Frontend switch to enable /disable access

### ISSUE THREAD

**Issue by PeterS1556** [arthurdent75/SimpleScheduler#166]
I like your scheduler, and have used it to control my multiple minisplits for nightime setbacks.  I want to be able to disable the warm up schedule entries for when I am away, by switching a single device, so I set up the MQTT config, per your instructions, and enabled it in SimpleScheduler, including username and password.
However, when trying to create a script to enable/disable, I cannot find an option in the action dropdown to access SimpleScheduler items.
I am a complete newbie to HA, so I am likely missing something obvious, but any pointers would be appreciated!

**Comment by PeterS1556** [comment]
Thanks!  When I look for the switches in developer tools-states, the SimpleScheduler switches are not present, only the update switches.  Any thoughts on what I might have missed in setting up MQTT?  I tried to follow your directions faithfully, but suspect I have not done something that would be obvious to a seasoned HA user..

**Comment by PeterS1556** [comment]
Some additional info:  I realized that the password would not be accepted into the password field when in the config screen for MQTT.  I tried uninstalling and reinstalling MQTT, but when I enter core-mosquitto for the server, and my HA username and password, after about a 5 second delay, I get the message:  
MQTT 
Please enter the connection information of your MQTT broker. 
Failed to connect
Definitely moving backwards here!

**Comment by PeterS1556** [comment]
Uninstalled and reinstalled both Mosquitto and MQTT, that all now seems to work.  I created a new schedule entry, thinking it may have to be created after MQTT is set up, but still not showing up as a switch in "states".  Is there any way to "ping" the MQTT pathway to determine whether it is configured correctly?

**Comment by arthurdent75** [comment]
First, take a look at the bottom of the scheduler list and check that simplescheduler successfully connect to MQTT
![image](https://github.com/user-attachments/assets/937f98e8-522a-4d15-8191-cdc244c53be8)

**Comment by PeterS1556** [comment]
Ah, thanks.  I hadn't noticed that whole line!  No, it says Disconnected.

**Comment by PeterS1556** [comment]
Given our time zone lag, I thought I would give you everything I had on this.  Thanks very much for your time!  I will definitely owe you a beer!

In SimpleScheduler , the enabled check box within the config screen is checked, and I have done multiple restarts, as I have tried every combination of user/password I could think of: my HA user and password, both fields empty, just "homeassistant" in the user field, pw field empty.  It says "(need restart)" to the right of the MQTT enabled checkbox, but I think that is a prompt, rather than a status indicator.
In MQTT, the only MQTT config that will load seems to be my HA user name, and nothing entered in the pw field.  The pw field self populates with   __**password_not_changed**__ , and that field will not accept my HA user password.  If I enter my HA password, the config fails.
I don't see any config options for Mosquitto.

**Comment by arthurdent75** [comment]
Let's try this: just create a secondary user in Mosquitto.

Go to _Setting_ --> _Add-ons_ --> _Mosquitto Broker_ --> _Configuration_
![image](https://github.com/user-attachments/assets/02472050-25e8-4534-a716-a6b2f6950767)
Fill the _Logins_ box as per screenshot, replacing mqtt_dedicated_xxxx with credentials of your choice.
Click _save_ and restart the Mosquitto addon.

After that, go to simplescheduler config and use the new credentials.
Restart the simplescheduler addon.

Finger Crossed! 🤞

**Comment by PeterS1556** [comment]
Yes!  Thank-you so much!  Enjoy the beer!
