### ISSUE TITLE
Could you please add an option to change the climate mode (heat/cold/ventilation/automatic)

### ISSUE THREAD

**Issue by htht2001** [arthurdent75/SimpleScheduler#167]
Could you please add a feature that allows changing the operating mode (heat/cold/ventilation/automatic) of the air conditioner, in addition to adjusting the temperature?

Thanks for the excellent plugin

**Comment by arthurdent75** [comment]
This will be very unfriendly in the command.
I think it would be easier to create a script that does all the settings and then call the script from the scheduler.
