### ISSUE TITLE
Scheduler process crashed...

### ISSUE THREAD

**Issue by st2000** [arthurdent75/SimpleScheduler#169]
Installed Simple Scheduler several days ago on HA w/these versions:
```
Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1
```
SimpleScheduler is to control 2 lights on/off every day of the week. After several days where the lights were never turned on/off automatically, I checked the log. I appears SimpleScheduler is always crashing (one a minute):
```
[07:14:00] INFO: Starting service.d [Scheduler]
[07:14:00] INFO: Running scheduler.sh
Traceback (most recent call last):
  File "/simplescheduler/scheduler.py", line 70, in <module>
    event_time = main.evaluate_event_time(t, sunrise, sunset)
  File "/simplescheduler/main.py", line 823, in evaluate_event_time
[2024-09-25 07:14:01] STATUS: Starting scheduler
    if 0 <= int(hm[0]) < 24 and 0 <= int(hm[1]) < 60:
ValueError: invalid literal for int() with base 10: 'MINUTES'
[07:15:00] WARNING: Scheduler process crashed...
[07:15:00] INFO: Restarting...
```
As a test, I will remove using time-of-sunset from the entries and see if that provides a temporary fix. 

If it does, I will post a follow up.

**Comment by arthurdent75** [comment]
@st2000 you probably made some syntax error. 
Can you post a screenshot where I can see the scheduler time?

**Comment by st2000** [comment]
I changed the time entries to "sunset + 30" and restarted the Developer tools -> SCHEDULE YAML.  I inspected the log (Scheduler -> log-icon) saw these new log entries:

> [2024-09-26 06:45:00] SCHED: Executing OFF actions for [garage]
> [2024-09-26 06:45:00] SCHED: Turning OFF [Garage Light] 
> [2024-09-26 06:45:05] SCHED: [Garage Light] is OFF as requested!

.. so I think that fixed the "errors in the log" problem.
