### ISSUE TITLE
Fatal error: Unknown: Failed opening required '/var/www/html/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0

### ISSUE THREAD

**Issue by Flop2006** [arthurdent75/SimpleScheduler#17]
On an installation of hass.io on a Synology Nas, I get the following error:

`Warning: Unknown: failed to open stream: Permission denied in Unknown on line 0
Fatal error: Unknown: Failed opening required '/var/www/html/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0`

The log says:

`[Sat Aug 01 21:13:30.178520 2020] [mpm_prefork:notice] [pid 12] AH00163: Apache/2.4.38 (Debian) PHP/7.3.20 configured -- resuming normal operations
[Sat Aug 01 21:13:30.179544 2020] [core:notice] [pid 12] AH00094: Command line: 'apache2 -D FOREGROUND'
172.30.32.2 - - [01/Aug/2020:21:13:30 +0200] "GET / HTTP/1.1" 200 463 "http://192.168.2.221:8123/hassio/ingress/00185a40_simplescheduler" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"`

Other addons work flawless.
Any idea why its doesn´t work?

**Comment by arthurdent75** [comment]
It looks like a permission issue.
But it seems to be related to your specific setup
