### ISSUE TITLE
Add change brightness without turning on

### ISSUE THREAD

**Issue by Strux-DK** [arthurdent75/SimpleScheduler#174]
I want to control the brightness of my lights throughout the day, in specific time slots. However, i don't want to turn them on, i want them to receive a new brightness level whether or not they're turned on or off. Your addon is the closest i've come so far, without doing it manually in code, but the feature of changing brightness without changing the on/off state is missing. Would it be possible to add that?

**Comment by arthurdent75** [comment]
Home Assistant does not support this.
The "_set_brightness_" command can only be called by the "_light.turn_on_" service.
