### ISSUE TITLE
Don't run scheduler for certain days

### ISSUE THREAD

**Issue by pboesch** [arthurdent75/SimpleScheduler#175]
Hey!

Im using simplescheduler to run climate entity for my office heater. It's working fine. 

But, i'm looking for a way not to run this scheduler on some predefine dates (example: holidays, day off).

How to accomplish this?

Thanks!

**Comment by arthurdent75** [comment]
create a "workday" binary sensor:
https://www.home-assistant.io/integrations/workday/
then put this template condition:
`{{  states('binary_sensor.workday) | bool }}`
