### ISSUE TITLE
Can't add to HACS

### ISSUE THREAD

**Issue by MassakerGU** [arthurdent75/SimpleScheduler#20]
Every time I try to add it in HACS there is an Error: Repostitory structure for master is not compliant.
I reinstalled HACS completly but no success.

Best Regards

**Comment by woodmj74** [comment]
Experiencing the same issue:
![image](https://user-images.githubusercontent.com/68328701/92577792-f814bb80-f282-11ea-8216-3996fec5bc1b.png)

**Comment by arthurdent75** [comment]
You can't, because it is not an HACS addon!
Simple Schedule is a native addon.
You have to add in
Supervisor -> Add-on store -> (top right three dot) -> Repositories -> Add Repository
