### ISSUE TITLE
Multiple scenarios

### ISSUE THREAD

**Issue by tux240** [arthurdent75/SimpleScheduler#21]
Thanks for this add-on.
I would like to create multiple scenarios like to switch on/off my heater for 15 minutes each hour but depend on the season.
So, in winter I need more schedulers than spring.

Is it possible to do that with your add-on ? 

Thanks

**Comment by arthurdent75** [comment]
Sadly, no.
It works on a weekly schedule.
What you can do is to create an automation/script that starts your heater based on seasons (using the "wait" or the time conditions), and then call the automation/script with Simple Scheduler
