### ISSUE TITLE
Web UI error

### ISSUE THREAD

**Issue by nikosiaf** [arthurdent75/SimpleScheduler#23]
Hello,

I get the following error when trying to open the web ui:

Warning: Unknown: failed to open stream: Permission denied in Unknown on line 0
Fatal error: Unknown: Failed opening required '/var/www/html/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0

Kind regards,
Nikos

**Comment by arthurdent75** [comment]
All this "Unknown" and "permission denied" let me think that something went wrong during the installation of the docker images called by the addon... I don't have enough data to help you with that.
