### ISSUE TITLE
error

### ISSUE THREAD

**Issue by danygi79** [arthurdent75/SimpleScheduler#24]
after update Home Assitant the error appeared Warning: file_get_contents(/data/options.json): failed to open stream: Permission denied in /var/www/html/lib.php on line 11

how can i do to fix it?

**Comment by DanBendavid** [comment]
+1

**Comment by leoyangt** [comment]
+1 no help with uninstall addon->reboot->install addon->reboot

**Comment by danygi79** [comment]
no result with addon-> restart-> install addon-> restart, the error remains the same and it is no longer possible to change the settings already entered

**Comment by arthurdent75** [comment]
duplicate #25
