### ISSUE TITLE
Permission denied -  Current version: 0.15

### ISSUE THREAD

**Issue by DanBendavid** [arthurdent75/SimpleScheduler#25]
Got this error 
Warning: file_get_contents(/data/options.json): failed to open stream: Permission denied in /var/www/html/lib.php on line 11

**Comment by Boia11** [comment]
Same error

![Screenshot_20201027-013833.jpg](https://user-images.githubusercontent.com/10048197/97242928-6262ca80-17f5-11eb-8893-1c74e3451d8c.jpg)

**Comment by PierreScerri** [comment]
Same issue.

Maybe it's related to the Daylight saving issue?

**Comment by arthurdent75** [comment]
The **/data/options.json** is the file used to share the add-on parameter (in the addon page) to the addon itself.
In some HA update probably they changed the file/folder permission and this file is not accessible anymore from the addon.
I have figure it out and I'm currently working to solve this issue.
Thank you for your patience.
Stay tuned!

**Comment by PierreScerri** [comment]
Great.  Thank you.

**Comment by edpvic** [comment]
Hello Arthuden75,

I have two servers running with this add-on (simple and easy, well done),  both are on the same HA release 0.116.4, in one of them the Add-on is running fine and the other one show this fault..... bellow you can see the options.json file permission in both cases:

options. json 101 Visual Studio Code Document 10/18/2020 -rw-r--r--  root root (it's ok)

and,

options. json 102 Visual Studio Code Document 10/25/2020 -rw-------  root root (faulty)

As you state the fault must be related to permissions.

Regards!!
Vic

**Comment by arthurdent75** [comment]
Fix released.
Should work now

**Comment by leoyangt** [comment]
tks
it's good on 0.117version

**Comment by Boia11** [comment]
Thanks! Good work!
