### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by gribouk** [arthurdent75/SimpleScheduler#27]
I have installed the add-on. When I create a test shedule and wait for the time set - nothing happens. While the ordinary way of setting the automation works (if time then activate the sceene).

**Comment by arthurdent75** [comment]
Can you give me some more detail? 
Entity used, maybe some screenshot

**Comment by gribouk** [comment]
![screen1](https://user-images.githubusercontent.com/72703085/97504874-da152e80-1988-11eb-85ae-75822c413e14.jpg)

**Comment by gribouk** [comment]
this is the switch example. My local time 0:34. I set 0:35 tu turn off every day - nothing happen. I go to automation and call tur off service for the same switch next minute and it goes to off...

**Comment by arthurdent75** [comment]
Left click on the word "scheduler" in the bottom gray status bar, just before the word "RUNNING".
You will get a popup with the timezone and server time

**Comment by gribouk** [comment]
yep, the time is right, the app still yelds no result - time passes, does not turn off

**Comment by gribouk** [comment]
I know the answer. You cannot write 1:05, you have to write 01:05... Maybe it will help someone else who encounters same problem.
