### ISSUE TITLE
sunset - sunrise offset

### ISSUE THREAD

**Issue by danygi79** [arthurdent75/SimpleScheduler#29]
Hello,
I need to turn on some lights 30 minutes after sunset and turn them off 30 minutes before sunrise, but I haven't found a way to do it, is it possible to implement this function?

**Comment by epmsmid** [comment]
First thanks for the great plugin! I was also looking for an offset to sunrise and sunset.
Perhaps it's an option to add a feature (sunrise|sunset);offset((+|-)hh:mm).
Perhaps another feature: add a feature to create a random offset from the specified time foreach switch, for both fixed times and sunrise/sunset. E.g. HH:MM;randomize(hh:mm), which set a random time starting at HH:MM, where hh:mm is the maximum random offset. Thi feature can also be used in combination with sunrise/sunset.

Example:
22:00;randomize(0:30) -> Create a random time between 22:00 and 22:30
22:00;randomize(1:45) -> Create a random time between 22:00 and 23:45
sunrise;randomize(1:00) -> Creata a random time between <sunrise> and <sunrise + 1 hour>.
sunrise;offset(+0:30);randomize(0:15) -> Create a random time between <sunrise + 30 minutes> and <sunrise + 45 minutes>
sunset;offset(-0:30);randomize(0:15) -> Create a random time between <sunrise - 30 minutes> and <sunrise - 15 minutes>

**Comment by supercazzola** [comment]
yes, it would be a very helpful option to be able to say turn on at sunset, turn off at sunset +HH:MM:SS (offset).

**Comment by arthurdent75** [comment]
This is the most required enhancement. I will keep that in mind!

**Comment by JohanNicander** [comment]
Sorry for necromancing this thread. I really like the plugin and I use the sunrise/sunset functionality a lot. But as suggested by @epmsmid it would be good to have a +/-rand(10) to randomly offset lights from a fixed schedule. Is this something that could be added do you think?
