### ISSUE TITLE
Reset to defaults does not work

### ISSUE THREAD

**Issue by akasma74** [arthurdent75/SimpleScheduler#3]
Just tried on 0.0.8

**Comment by arthurdent75** [comment]
"Reset to default" is a Home Assistant procedure, not related to the addon.
Can you add a screenshot of your configuration area?

**Comment by akasma74** [comment]
I didn't know that. Anyway, it doesn't work - I just _removed_ unnecessary keys/values
![Screen Shot 2020-02-26 at 11 13 11 (2)](https://user-images.githubusercontent.com/13675855/75339870-40413300-5889-11ea-81b7-c7b9118b8db3.png)
hit `SAVE` and there you go
![Screen Shot 2020-02-26 at 11 13 26 (2)](https://user-images.githubusercontent.com/13675855/75339886-49ca9b00-5889-11ea-8f46-c0992ca77263.png)

**Comment by arthurdent75** [comment]
You don't have to remove it.
You have to set them to _false_

**Comment by akasma74** [comment]
> You don't have to remove it.

well, I thought it's ok if I remove them ;)
mainly because when I do something like that, I presume that "no key" menas "key: false"

> You have to set them to _false_

That's exactly the problem - I hoped that RESET TO DEFAULTS would load the defaut config but no, it does not (so my only option is to type in the deleted stuff manually - a bit stupid, right?).

And if you think about further releases, how are you going to support it if something is added and something else goes? It might be a deadlock.

**Comment by arthurdent75** [comment]
Yes, you're right.
I've just replicated your actions and I have same behaviour.
Give me some time to figure it out.

**Comment by arthurdent75** [comment]
I think it is a Home Assistant "normal" behaviour

https://github.com/home-assistant/supervisor/issues/278

_Reset to default_ discard changes, doesn't "rebuild" deleted configuration options.

**Comment by akasma74** [comment]
I see.
Don't know why they coulnd't implement it more "human" way.
Oh well..
Thanks for looking into it anyway!
