### ISSUE TITLE
Cannot control the same entity with several config

### ISSUE THREAD

**Issue by ptibubu** [arthurdent75/SimpleScheduler#30]
Controlling the same entity several times does not seem to work: only the last config is actually applied.
Ex for the same input_boolean:
1: On at 8:00, off at 9:00
2: On at 15:00, off at 15:00

It looks like only 2: is applied.

**Comment by arthurdent75** [comment]
In the past, I had the same entity with 3 different scheduling and it was working...
I will run some new test!
