### ISSUE TITLE
I coludnt run it

### ISSUE THREAD

**Issue by adnn-hassio** [arthurdent75/SimpleScheduler#32]
Arthurdent, thanks so much for this pure, simple and useful code. But whe i test it i cant take any action. I had Sshots. I want to open and close some switch when i need in time.
![IMG-0767](https://user-images.githubusercontent.com/76571009/103760587-5af64380-5026-11eb-827d-ebe61f063d46.PNG)
![IMG-0766](https://user-images.githubusercontent.com/76571009/103760613-6184bb00-5026-11eb-9e50-c69dd86c2232.PNG)

**Comment by arthurdent75** [comment]
The time format is HH:MM
Remove the seconds
Use leading zero for hours
