### ISSUE TITLE
Multiple On and Off entries per device?

### ISSUE THREAD

**Issue by plbartie** [arthurdent75/SimpleScheduler#33]
Hi
I love how simple the program is and is exactly what I've been looking for. Good work.
Would it be possible to add multiple on and off times per entry? example:
Turn on: 09:00 / 12:00 / 15:00 / 18:00 
Turn off:  11:00 / 14:00 / 17:00 / 20:30

Maybe it is possible but I don't know the delimiter?

**Comment by arthurdent75** [comment]
No, you can't. Sorry.
