### ISSUE TITLE
Warning: file_get_contents(/share/simplescheduler/options.json): failed to open stream: Permission denied in /var/www/html/lib.php on line 11

### ISSUE THREAD

**Issue by Nicols07** [arthurdent75/SimpleScheduler#35]
My HA is a Docker HASSIO install on NAS Synonlogy.

For info, this is running : https://github.com/danielwelch/hassio-zigbee2mqtt

Regards.

Nico.

**Comment by dubhunter** [comment]
Also getting this on fresh install.

**Comment by arthurdent75** [comment]
This is very odd behavior. It never occurs to me,
BTW, the new release (0.20) should manage this error and go on.
