### ISSUE TITLE
Hide entities

### ISSUE THREAD

**Issue by gitprova0** [arthurdent75/SimpleScheduler#36]
Hi, I'm new here. I really appreciate your work.

I want to ask you if it is possible to hide some entities.
I tried to set, in the addon configuration panel, a true/false parameter for the entities I want to control/hide, but nothing seems changing.

The purpose of this functionality is because I want my family components able to control only certain entities and not all of them.

Thanks.

**Comment by arthurdent75** [comment]
Thank you for your suggestion.
I will keep that in mind
