### ISSUE TITLE
couple requests for the program

### ISSUE THREAD

**Issue by comet424** [arthurdent75/SimpleScheduler#37]
hi so i not sure how to really edit codes to make it work for me
but wanted to see

1.. your scheduler has teh green toggles to enable disable.. anyway to make them  clickable.. instead of only when u click the Edit and then enable the check box?

2..  i have a pump i use an arduino and  i use momentarty switch to on and off...  id like option  for your program to have a Start script and end script
so say  8:00pm  runs  toggle.script     (turns it on)     and at 8:05     toggle.script     (turns it off)  instead of needing to lines of code.

3.  before home assistant i use  Crontabs   and i made a simpler thing for me .. that every 2 hours  it would run a script and every 2 hours 15 min    would run script again to shut off..      or i had one for ever 4 hours..  and  i just rem out  the 2 lines   
is there a way you can also incorporate   Crontab  so i could have 1 line of scheduler that will run every 4 hours or ever 2 hours..   and then the 2nd line  would be my shut off   so ever 4 hrs 15 min   or ever 2 hours 15 min..  if you need to see my crontab  on what i mean i can send it later 

so far i struggling to learn  Home assistant  and lot of times bashing head off wall lol..  no real good step by step tutorials

but i figured id ask

**Comment by arthurdent75** [comment]
Hi @comet424
1) It's a choice to not edit any parameter from the home page, to avoid false command especially when using the app on a mobile device
2) With the new release (0.20) you will solve this. Just write both times in the turn-on field
3) Sorry... this requires major changes. But with the new release (0.20) you could add as many turn on/off time as you like.

Ciao
