### ISSUE TITLE
Version 0.21 doesn't work under Nabu Casa

### ISSUE THREAD

**Issue by KixMan28** [arthurdent75/SimpleScheduler#38]
Since I have installed the latest versions (ver 0.20, 0.20.01 and 0.21) I have the same issue: if I connect to my HA instance via Nabu Casa (HA ver core-2021.4.6, supervisor-2021.04.0) in the Simple Scheduler UI none of the buttons work and web UI looks strange (see attached screenshot)

![2021-04-24 11_18_32-Action center](https://user-images.githubusercontent.com/33165356/115954030-01d7f000-a4ef-11eb-9e42-0be9c118218d.jpg)

If I access the HA locally the Simple Scheduler works fine and the buttons also execute their task, but the switching on and off won't execute at the set times.

What is causing this?

**Comment by Andream69** [comment]
I confirm I use Nabu Casa and it doesn't work. It is not possible to create new automations and you cannot modify existing ones. Help me ArthurDent1975.

**Comment by arthurdent75** [comment]
I don't have NABU CASA so it is hard to me to debug. 
Surely it looks like something went wrong with the CSS file. There is a way to somehow clear the cache in NABU CASA?

> If I access the HA locally the Simple Scheduler works fine and the buttons also execute their task, but the switching on and off won't execute at the set times.

Please, from local instance take a look at the bottom gray bar and check the TIME ZONE
![image](https://user-images.githubusercontent.com/60071192/115960668-11693000-a513-11eb-9600-742fc418159d.png)

**Comment by Andream69** [comment]
It was enough to uninstall and reinstall the addon and everything works perfectly. 
![Immagine 2021-04-24 162712](https://user-images.githubusercontent.com/59484530/115962119-21384280-a51a-11eb-8253-63bfedf8300f.png)

**Comment by KixMan28** [comment]
@arthurdent75 in the local instance the time zone is correct.
@Andream69 I will try to reinstall the add-on right now.

**Comment by KixMan28** [comment]
@arthurdent75 @Andream69  the uninstall and reinstall solved the issue. I think it is worth mentioning it in the changelog or readme, so also others are aware of this. On the other hand would be good to have a look into this issue, because there is definitely  a bug somewhere in the code.

**Comment by arthurdent75** [comment]
@Andream69 @KixMan28 thank you for helping me to debug this.
It happened in the past that few HA supervisor updates changed permission on the shared folders, preventing my addon to read data. The addon fixes this during the setup, but it can't do that after installation. 

My guess is that HA manages the update differently from a "scratch" installation when it comes to addons.
Technically the process should be the same, but this is not what seems to happen indeed.

@KixMan28 I will write that in the FAQ but I don't think this is some bug I could fix in the code.

Any further and future hints will be appreciated
Thank you both!

**Comment by Andream69** [comment]
@arthurdent75 Thank you for creating this addon.

**Comment by KixMan28** [comment]
@arthurdent75 Thank you. I am closing now this issue.
