### ISSUE TITLE
Addon to heavy 

### ISSUE THREAD

**Issue by TLongstride** [arthurdent75/SimpleScheduler#39]
When supervisor make an snapshot and i have only one programmation inside the snapshot does 115 mo !

How it is possible ? Could you explain me ?

**Comment by arthurdent75** [comment]
The addon itself is really lite... few and small files. 
You can see that by yourself looking in the file repository.
Have you tried to uninstall the addon and make the snapshot again?

**Comment by TLongstride** [comment]
I tried, same result.

It seems that the snapshot take home assistant and note only the addon, but that doesnt do it for other addon snapshot

Any idea ?

**Comment by arthurdent75** [comment]
Yes, the snapshot takes the whole system. This is completely normal!
I thought you mean that your snapshot was 115MB bigger after installing my addon!  

Many other add-ons ask for a snapshot, so you can revert back in case of trouble.
If you don't want to, just uncheck the bottom-right slider.

No issue, then. Closing this!
