### ISSUE TITLE
Input booleans

### ISSUE THREAD

**Issue by samnewman86** [arthurdent75/SimpleScheduler#4]
Please add support for input_boolean.
For myself this would be the most useful thing to have in simple scheduler, and it shouldn't add any complexity.

**Comment by arthurdent75** [comment]
Please, explain to me how should it works. It is not clear to me.

**Comment by arthurdent75** [comment]
Done

**Comment by samnewman86** [comment]
Thanks so much for your hard work.
My code suggestion seemed close, what did i miss?
