### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by tbkurtz** [arthurdent75/SimpleScheduler#40]
I'm trying to add multiple devices to a single rule, but the plus button doesn't seem to do anything.

**Comment by tbkurtz** [comment]
I tried restarting the addon, and reinstalling.  I am running HomeAssistant via HASSOS VM running in UnRaid.

**Comment by arthurdent75** [comment]
This is odd. Seems a cache problem. Have you tried to clear the cache? Have you tried other browsers?

**Comment by tbkurtz** [comment]
I tried using the the new chromium based edge, which should have nothing cached (because I never use it) and saw the same behavior.

**Comment by arthurdent75** [comment]
I'm about to release a new version with new features.
Please, be patient for a little while, and let's see what happens with the new release. 😄

**Comment by tbkurtz** [comment]
Sounds good! When will it be released?

**Comment by arthurdent75** [comment]
> Sounds good! When will it be released?

Now! 😄
