### ISSUE TITLE
HASSIO web ui bootstrap error

### ISSUE THREAD

**Issue by luca-san-dev** [arthurdent75/SimpleScheduler#42]
I got this error each times i open the web-ui. 
I already tryed to reinstall and rebuild the package wo success.

This error makes the entire component not working.

VM652 bootstrap.min.js:6 Uncaught TypeError: Cannot read property 'fn' of undefined
    at VM345 bootstrap.min.js:6
    at VM345 bootstrap.min.js:6
    at VM345 bootstrap.min.js:6
    at VM345 bootstrap.min.js:6

Tested Browsers: Google Chrome - Ms Edge

**Comment by arthurdent75** [comment]
Can you please confirm that if you remove the addon the error disappear from the console?

**Comment by luca-san-dev** [comment]
> Can you please confirm that if you remove the addon the error disappear from the console?

Yes! It appears only when you open the component web-ui. 

I think it's striclty related to the other opened issue on this board.

**Comment by arthurdent75** [comment]
I was asking that because I have similar errors in the browser console, but the addon is working anyway

**Comment by saltafossi** [comment]
Ciao!
I also have this error:
```
Uncaught TypeError: t.fx is undefined
    jQuery 7
jquery-ui.min.js:6:23542
```
Then if I click on the + button the sidebar is empty and I get this error:

`Uncaught TypeError: $(...).load is not a function`

Maybe this helps..

**Comment by arthurdent75** [comment]
Ciao @saltafossi  Thank you for your help.
I think we can consider this as the same issue as #41 
So let's move there

**Comment by luca-san-dev** [comment]
Thank you so much!

🤟

Il dom 18 lug 2021, 08:48 arthurdent75 ***@***.***> ha
scritto:
