### ISSUE TITLE
Can't edit anything. Addon suddenly broken: White/Blank page on editing

### ISSUE THREAD

**Issue by ad1k4h** [arthurdent75/SimpleScheduler#43]
Dear Developer,

i've using your addon for long time, and its suddenly broken. When i would like to edit an existing automation (or add a new), on the right side panel, where i can make the editings is now Blank (White). I tried to uninstall/reinstall or Rebuild.

**Comment by ad1k4h** [comment]
Addon ver: 0.30.04
Home Assistant 2021.7.3

**Comment by arthurdent75** [comment]
Duplicate #41
