### ISSUE TITLE
Errors when device/entity names include single quotes

### ISSUE THREAD

**Issue by matt-sullivan** [arthurdent75/SimpleScheduler#44]
If an device/entity name includes a single quote there are syntax errors in the index.php script and as a result none of the buttons work.

I'm not sure if it's device or entity names that's causing the problem, but I can confirm that renaming my devices and entities did workaround/fix the problem for me. Version 0.30.05, tested in both chrome & firefox with HA 2021.6.6.

**Comment by arthurdent75** [comment]
Thank you @matt-sullivan, you are right, I confirm the bug.
I will fix it in the next release.

**Comment by arthurdent75** [comment]
Fixed in 0.31
