### ISSUE TITLE
Not able to add any schedules

### ISSUE THREAD

**Issue by craigmcewen** [arthurdent75/SimpleScheduler#45]
I've just installed the scheduler and it appears to install into HA ok, I can see it has created some files in the Samba share etc, I go into the web ui for the scheduler and it shows running along the bottom but nothing happens when I click the + button at all. I have tried a restart on HA as well as clearing browser cache and it has not seem to have resolved either. 
Any ideas what I have potentially done incorrect?

**Comment by Energyboost** [comment]
same issue https://github.com/arthurdent75/SimpleScheduler/issues/41
