### ISSUE TITLE
Enable or disable schedules with an automation

### ISSUE THREAD

**Issue by rogeralexanderdean** [arthurdent75/SimpleScheduler#50]
Hi there, love this add-on, helps get the kids up on weekdays!
We have an automation that turns everything off with one click when we go on holiday. It would be great to be able to also disable the schedules from within that automation. Can it be done? Many thanks

**Comment by arthurdent75** [comment]
I'm glad you like the addon.
What you ask cannot be done within the addon. It requires a **custom integration** which should be installed separately.
This is something I'm currently working on, because I need it too.
I cannot give you a deadline, tho.
Cheers!
