### ISSUE TITLE
Just set the temperature

### ISSUE THREAD

**Issue by jrousek** [arthurdent75/SimpleScheduler#51]
Now:
*You can set the temperature of a climate. Write 16:30>T22.5 turn on the climate and set the temperature to 22.5°

This change on my TVR "current_heating_setpoint: 22.5". Is ok. But at the same time it changes the state on heating. 

This causes the TVR to open the valve to 100% and not turn off the valve even when the temperature is reached. 

my suggestion is to add to the settings the ability to enter for example 16:30> OT22.5 (only temperature 22.5) which would set only "current_heating_setpoint: 22.5"

Would this be possible?  I will be happy to give you the beer to work.

Jrousekcz from czech (beer country) :)

**Comment by arthurdent75** [comment]
Hi @jrousek the addon calls two services, indeed:

- _climate.turn_on_
- _climate.set_temperature_

what you ask is a way to call only the _climate.set_temperature_ service, right?
Can you try to simulate the service _climate.set_temperature_ from Developer Tool and test if this achieves what you ask?

**Comment by jrousek** [comment]
yes, only the "climate.set_temperature" command works well for me
![Screenshot_20220126-201552_Home Assistant](https://user-images.githubusercontent.com/51027578/151231049-2560f3c3-b66c-4ed1-99ad-62c2b8778e8a.jpg)

**Comment by jrousek** [comment]
Thank you for dealing with my problem.  Cheers! ;)

**Comment by arthurdent75** [comment]
Version 0.34 is on its way
