### ISSUE TITLE
Don´t turn device off

### ISSUE THREAD

**Issue by jiripaskov** [arthurdent75/SimpleScheduler#52]
Hello. First I want to say your scheduler is awesome. Good work. I would like to use previously implemented function to not turn ON (heating) device with temperature set during ON procedure. Could it be possible also not to set OFF device (not to call climate.turn_off) on adjusted time but make temperature change if there will be something like "19:56>T27" in "OFF" field? Thanks.

**Comment by arthurdent75** [comment]
If I understand correctly, you want to change the target temperature while the heating is OFF.
You can do it by setting in the ON section 19:56>**TO**27 
(TO stand for _Temperature Only_)
This set the temperature no matter what. If the heater is ON it will remain on. If the heater is OFF it will remain off.

For example in this scenario:
**ON section**
18:00  19:30>TO27
**OFF section**
19:00
the climate will turn on at 18:00 with the last target temperature
then the climate will turn off at 19:00
after that, the target temperature will be set at 27° at 19:30 when the climate is already off (and it will remain off)

Hope this is what you were looking for

**Comment by jiripaskov** [comment]
Nope. I want only tgo change temperatures. At 18 to 27° and at 20 to 23°. Next day the same... Without device state changing (on/off). Only to set target temperature.

**Comment by arthurdent75** [comment]
Then you just need to write in the ON section
18:00>TO27  20:00>TO23 
Leave empty the OFF section
That's it!

**Comment by jiripaskov** [comment]
Oh nice. Working, Thank you very much!
