### ISSUE TITLE
Temperature Only does not work for two climates in the same scheduler

### ISSUE THREAD

**Issue by jrousek** [arthurdent75/SimpleScheduler#53]
This will set the "Termostatická hlavice dětský pokojíček" temperature to 22.0 correctly. But on "Termostatická hlavice obyvák" the temperature does not set and starts climate.turn_on

![Snímek obrazovky 2022-01-29 072517](https://user-images.githubusercontent.com/51027578/151650443-ba2e8539-49f4-46ee-86c6-e4d51d2e855d.png)

**Comment by arthurdent75** [comment]
You are right. I found the bug. Working on next release

**Comment by arthurdent75** [comment]
Version 0.35 is on its way
