### ISSUE TITLE
Holiday functionality

### ISSUE THREAD

**Issue by Kettenknecht** [arthurdent75/SimpleScheduler#55]
Can we get a holiday functionality, or at least, a switch for every schedule to turn it off? This would be great.

**Comment by arthurdent75** [comment]
You already have a switch to turn it off!
Just edit the scheduler and remove the checkmark from "Enabled"
![image](https://user-images.githubusercontent.com/60071192/155888073-c23eef87-9006-4186-bbac-fdfe8a1e06f0.png)
The scheduler will stay there, grayed, and it won't be executed until you enable it back again.
