### ISSUE TITLE
enhancement request : condition

### ISSUE THREAD

**Issue by Brun059** [arthurdent75/SimpleScheduler#56]
I have you famous scheduler  switching on a heater, as well as an automation triggered by surplus solar power.

The scheduler switches of (let's say at 7:49 as scheduled) even though I have surplus solar power since 7:30.

Is there a way to add conditions into a scheduler,  e.g switch on/off only if some condition met/not met?

**Comment by arthurdent75** [comment]
Sorry to disappoint you, but no. 
I should change the name of the addon and remove the word "_simple_" from it 😉 
But you can achieve that with a simple automation or script, that you could fire from the scheduler.

**Comment by arthurdent75** [comment]
@Brun059 what you asked is actually in beta (better late than never 😅 )
https://community.home-assistant.io/t/simple-scheduler-addon/174326/440
