### ISSUE TITLE
New Requirement - Weekly schedule graphic improvements

### ISSUE THREAD

**Issue by gabrio79** [arthurdent75/SimpleScheduler#57]
First of all, thanks again for your (wonderful) job, the new feature (week) is very useful!
I'd like suggest you a minior graphical improvement, on weekly schedule
this is today if is set a large number of schedule
![Schermata 2022-03-18 alle 18 17 06](https://user-images.githubusercontent.com/65911264/159052087-a2b10aea-ff1f-4d46-a112-28157dd97691.png)
below is I suggest you, in some words, place stop sequence, near start instead of between
![Schermata 2022-03-18 alle 18 17 06](https://user-images.githubusercontent.com/65911264/159052818-a9595cd2-b2c3-4e92-8c6a-c154b7142a9c.png)

**Comment by arthurdent75** [comment]
Thank. I'm glad you appreciate my work.

In your example all times are "simple", they don't have any brightness or temperature attribute.
If you have a situation like this:
![logo](https://user-images.githubusercontent.com/60071192/159142036-c302085f-76fc-45ce-9526-5558b63d6c7b.png)
you may understand that that layout would be messy.
Anyway, thank you for your idea.
