### ISSUE TITLE
Feature requests: triggers and overrides

### ISSUE THREAD

**Issue by Klagio** [arthurdent75/SimpleScheduler#6]
Hi, I don't know how much time you have to program this. Already is a very cool addon. I propose you new feature which will be definetely cute additions, in case you have time (I am not able to help though for lack of skills).

Triggers: light turn of upon a sensor trigger, like this you will make thousands of people happy, basically one of the most common automation: turn on a light upon a PIR sensor trigger

Overrides: light turn ON (or OFF) only if a specific entity is ON (OFF). For example turn ON light on motion only if switch.TV is OFF

:

**Comment by arthurdent75** [comment]
I think this is way too far from the original concept.
What you ask is more near to automation than scheduling.
On a programming level, it means to impement an automation engine, which is difficult and also already fully implemented in HA.
Sorry, but I can't fulfill your request.
Ciao!
