### ISSUE TITLE
Enhancement: workday management

### ISSUE THREAD

**Issue by Gio-dot** [arthurdent75/SimpleScheduler#60]
Hi, Simplescheduler is now really complete and useful but there is something missing: workday management. It would be very useful to integrate the possibility to differentiate holiday and workday based on local calendar. I hope this feature can be added in the future.

**Comment by arthurdent75** [comment]
Interesting idea @Gio-dot 
From a UI perspective, how do you think this could be implemented?

Sadly, there isn't a native function in PHP to achieve that.
I have to dig around...

**Comment by Gio-dot** [comment]
> Interesting idea @Gio-dot From a UI perspective, how do you think this could be implemented?
> 
> Sadly, there isn't a native function in PHP to achieve that. I have to dig around...

To dig around you can use workday platform to determine workdays/holidays. It provide a simple binary sensor that you can use as condition in SimpleScheduler:
https://www.home-assistant.io/integrations/workday/

In the frontend a possible solution would be to add two checkbox to exclude workdays OR holidays from current scheduler scheme. For example if is created a scheduler for all the days of the week and i select "exclude workdays" that scheduler will work only in holidays.
![image](https://user-images.githubusercontent.com/55327160/160299685-a226e11d-a977-48a1-8b45-8387e23ba2f1.png)

**Comment by arthurdent75** [comment]
>  you can use workday platform to determine workdays/holidays. It provide a simple binary sensor
It's not so easy. This is a python function. The addon is written in PHP. In PHP there is no such function.
The use of a binary sensor implies that the user have to set it up and call it with a specific name, so I can retrieve it from the ADDON.
This is not straightforward

**Comment by Gio-dot** [comment]
> > you can use workday platform to determine workdays/holidays. It provide a simple binary sensor
> 
> It's not so easy. This is a python function. The addon is written in PHP. In PHP there is no such function. The use of a binary sensor implies that the user have to set it up and call it with a specific name, so I can retrieve it from the ADDON. This is not straightforward

Other scheduler are made in such way: user have to setup homeassistant workday integration to have it working in the scheduler. I don't think it is a problem. User don't have to give a specific name to the workday integration: it is a standard homeassitant integration named `binary_sensor.workday_today`.
Take a look at the famous [@nielsfaber scheduler ](https://github.com/nielsfaber/scheduler-card). It also require to setup workday integration in order to have it working in its  scheduler:
![image](https://user-images.githubusercontent.com/55327160/160416073-316cbb44-7db5-451f-b139-b1fb78d23722.png)

I think this is a normal requirement if you need to have workday management in the scheduler..

**Comment by arthurdent75** [comment]
Thank you for help me diggin in! 😉 
What you say is partially correct.
If you do not define a name in the binary sensor declaration, its name will be the default one.
But if you specify a name, LIKE I DID 😄, it could be different.
(in my case it is called _binary_sensor.giorno_lavorativo_)
So I have no clue to guess how every user called it.

One solution could be to add an entry in the addon configuration so you can specify the entity_id of the workday integration.
If the configuration entry is empty, no checkbox wil be shown.
And than pray that people will read the FAQ 🤣

**Comment by arthurdent75** [comment]
I started to add workday management in the code, but I faced this situation:
- some timers were bonded to holidays (e.g. the morning wake events)
- some timers were bonded to the day before the holiday (e.g. timer that turns off the tv for kids)

In this situation, I shall need two binary sensors: one "normal" and one with days_offset: -1
This requires that the code should handle multiple binary sensors.

So I decided to put my effort into managing the schedulers as switches from frontend and in automations.
This way I now have two automations: 
- one automation disables schedulers on holidays, bonded to one binary sensor
- one automation disables schedulers the day before holidays, bonded to the other binary sensor

Maybe it is not straightforward as you requested, but it is way more flexible...

The new release 0,50 is already out!

Ciao!

**Comment by Gio-dot** [comment]
I'm sorry but I do not understand why do you need to manage the days before holidays 🤔 Can you explain me a use case in detail?

**Comment by arthurdent75** [comment]
> I'm sorry but I do not understand why do you need to manage the days before holidays 🤔 Can you explain me a use case in detail?

I've already done that in the previous post: 😉 
> some timers were bonded to the day before the holiday (e.g. timer that turns off the tv for kids)

I have a timer that turns off TV at night for kid. 
It turns TV off at 21:00 on Su, Mo, Tu, We, Th (because they have school the day after)
It turns TV off at 22:00 on Fr,Sa (because they don't have school the day after)
It also turns TV off at 22:00 if the following day is an holiday (even if it is a working day)

**Comment by Gio-dot** [comment]
Ok, now i understand what you meant. Following this logic you should consider even the days following holiday, and even +1,+2 etc. ! I don't know, maybe a good implementation (I'm not 100% sure though) even if I'm not aware of other schedulers that implement this.
