### ISSUE TITLE
How to work mqtt? Not working?

### ISSUE THREAD

**Issue by jrousek** [arthurdent75/SimpleScheduler#63]
Hi,
perfect improvements mqtt me not working.  mqtt the simple scheduler communicates but the switch entity does not appear.  is there a mistake in me or somewhere else?
![Screenshot_20220411-194257_Home Assistant](https://user-images.githubusercontent.com/51027578/162800585-e49f775a-8f57-46d0-a49c-edefffb79169.jpg)
![Screenshot_20220411-194356_Home Assistant](https://user-images.githubusercontent.com/51027578/162800588-d83f0892-d1fd-4f89-972f-cc8fd33a4ef6.jpg)
![Screenshot_20220411-194658_Home Assistant](https://user-images.githubusercontent.com/51027578/162800590-baf5f712-cd58-4c36-992a-9c3ea7742712.jpg)
![Screenshot_20220411-194603_Home Assistant](https://user-images.githubusercontent.com/51027578/162800592-29845fde-66c9-4665-819e-ad18f1446256.jpg)
![Screenshot_20220411-194624_Home Assistant](https://user-images.githubusercontent.com/51027578/162800593-b97208b5-06ab-423f-b67a-b7de6b5158e7.jpg)
![Screenshot_20220411-195929_Home Assistant](https://user-images.githubusercontent.com/51027578/162801187-d8ea003c-1a55-442e-b1ac-ce7054d30440.jpg)
![Screenshot_20220411-200001_Home Assistant](https://user-images.githubusercontent.com/51027578/162801193-a367dc53-54fe-45fc-8c39-9fb3661ee5be.jpg)

**Comment by arthurdent75** [comment]
Looking at your pics, I can see that SimpleScheduler is talking with the broker and it is sending the discovery info.
The only clue is that the MQTT integration is not working or discovery is not enabled

Take a look at section 2 of the guide:
https://github.com/arthurdent75/SimpleScheduler/blob/master/asset/MQTT.MD#2-install-the-mqtt-integration

**Comment by jrousek** [comment]
I use zigbee2mqtt and when I add an entity there in the mqtt integration it will show up right away.  I have auto discovery turned on in mqtt

**Comment by jrousek** [comment]
I tried disabling mqtt in simple sheduler.  turn on again.  without success.  then re-configure mqtt integration.  without success.  restart the entire HA.  without success.

**Comment by jrousek** [comment]
mqtt overall works.  I have a zigbee thermohead on it that I constantly communicate via mqtt.  and other zigbee things communicate via mqtt.  for clarification.

**Comment by arthurdent75** [comment]
Ok... that's odd.
What user/password have you configured in zigbee2mqtt? It is the same you used in simplescheduler?
Also try to configure in simplescheduler the username/password you use to access Home Assistant

**Comment by jrousek** [comment]
tested.  without change.  restart and suddenly works.  I deleted the diacritics from the title.  switch entities are visible at once.  now I return the diacritical and works with it.  thanks for the help.  probably an error between the keyboard and the monitor. Thx

**Comment by arthurdent75** [comment]
Probably there is an issue due to your language. Please paste here a couple of titles with diatritics so I can test it.  Thanks 👍

**Comment by jrousek** [comment]
We used these names:
Pracovní týden obyvák
Víkend obyvák
Pracovní týden dětský pokoj
Víkend dětský pokoj
Everything was created about 3 versions back. And now after several updates running mqtt.

Addendum: Now everything works.

Thank you very much for this great accessory. Great job
