### ISSUE TITLE
warning if save weekly type

### ISSUE THREAD

**Issue by jrousek** [arthurdent75/SimpleScheduler#64]
When I save weekly type throws a warning message.
All weekly type they do.
SimpleScheduler it works, it just shows this when saved.

example:
![1](https://user-images.githubusercontent.com/51027578/164206809-014542d9-289e-4c86-af9d-19fc94b918a7.png)
![2](https://user-images.githubusercontent.com/51027578/164206816-1b8e26b8-07a1-4d1c-aeca-aa4b1a5374e0.png)

Ne - Čt - 04:30>TO20.0 06:30>TO19.0 14:15>TO20.0 22:00>TO19.0 (sunday - thursday)
Pá - So - 05:00>TO20.0 22:00 (friday - saturday)

**Comment by arthurdent75** [comment]
As a workaround while I investigate, set **debug:false** in the addon configuration

**Comment by jrousek** [comment]
Omg. I'm sorry, I didn't get it.  I am sending a beer 😉
