### ISSUE TITLE
Install/Update error in a linux supervised installation

### ISSUE THREAD

**Issue by bedmanforever** [arthurdent75/SimpleScheduler#65]
Hi,

I love your Hass add-on and running it die multiple purposes. Since simple scheduler 0.50 I cannot update the add-on anymore.
I receive the following error:

The command '/bin/sh -c apt update && apt -y install sudo' returned a non-zero code: 100

I tried to delete and reinstall it and even through the CLI directly. But installation leads to the same error without further information.

System info:
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.2
Kernel version 5.10.60-v7+

Can you check what ist the cause of this issue and how it can be fixed.

Thanks,

Michael

**Comment by bedmanforever** [comment]
> have you a supervised installation of Home Assistant with docker?

Yes, I have on a Raspi 2.

**Comment by user514** [comment]
Me too. On a Raspi 3.

**Comment by user514** [comment]
> This is related to the difference in docker base images. I have to create such kind of environment to test it out because I dev (and use) my addon on OS environment... thinking

  Thank you Arthur. I just keep un-updated until then... don't worry. Thanks for your great addon. Keep subscribed here...

**Comment by bedmanforever** [comment]
> This is related to the difference in docker base images. I have to create such kind of environment to test it out because I dev (and use) my addon on OS environment... 🤔

Cool, very much appreciated. Do you have an idea how I could use 0.40 in the meantime?

**Comment by arthurdent75** [comment]
> Do you have an idea how I could use 0.40 in the meantime?

You can download the 0.40 files from here
https://github.com/arthurdent75/SimpleScheduler/tree/d9f508e89e1d7f556ee3ef107e795d26173abee0
and install it as a local addon by coping the file structure in a subfolder named _SimpleScheduler_ under the _addon_ folder via SMB

**Comment by arthurdent75** [comment]
v0.60 is out!

**Comment by bedmanforever** [comment]
Thank you for your support. I tried to install it in my supervised Hass environment. Unfortunately I got now the following error message:
The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends apache2 php7.4 php7.4-curl php7.4-intl php7.4-mbstring php7.4-json' returned a non-zero code: 100

Good news I found out what caused the issue. I attached myself to the supervisor docker runtime and received the following error:

`
22-05-31 10:16:24 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build 00185a40/armv7-addon-simplescheduler:0.60: The command '/bin/bash -o pipefail -c apt-get update     && apt-get install -y --no-install-recommends            apache2                 php7.4          php7.4-curl             php7.4-intl             php7.4-mbstring                 php7.4-json' returned a non-zero code: 100
22-05-31 10:16:24 ERROR (SyncWorker_2) [supervisor.docker.addon] Build log:
Step 1/10 : ARG BUILD_FROM=ghcr.io/hassio-addons/debian-base/amd64:5.3.0


Step 2/10 : FROM ${BUILD_FROM}


 ---> 3d4dadaf14dc

Step 3/10 : RUN     apt-get update     && apt-get install -y --no-install-recommends            apache2                 php7.4          php7.4-curl             php7.4-intl             php7.4-mbstring           php7.4-json


 ---> Running in c6642921439f

Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]

Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]

Err:2 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.

Err:1 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.

Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.

Reading package lists...


W
:
GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.

W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.

E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
`
After digging a little deeper I found that this is an issue with Debian / Raspbian Buster installation. To fix it:

1. Add Buster Backport to our apt sources
2. Update libseccomp2

`sudo vi /etc/apt/sources.list
### Add the backports repo
deb http://deb.debian.org/debian buster-backports main

### Add GPG Keys
gpg --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
gpg --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
gpg --export 04EE7237B7D453EC | sudo apt-key add -
gpg --export 648ACFD622F3D138 | sudo apt-key add -

### Install libseccomp from backports:
sudo apt install -t buster-backports libseccomp-dev`

Reference: https://github.com/debuerreotype/docker-debian-artifacts/issues/122

**Comment by arthurdent75** [comment]
So there was nothing I could do to fix this, right? It was not related to the addon? Good to know 😅

**Comment by arthurdent75** [comment]
@bedmanforever thank you so much!
I will definitely add this in the FAQ

**Comment by andrejskorols** [comment]
> 

I have the same problem, I can't install this Add-On.
@bedmanforever , please give better instruction for your solution above.
We have 2 point:
1. Add Buster Backport to our apt sources  - What I should do it?
2. Update libseccomp2 - Have I add all text to file /etc/apt/sources.list

And what is it next steps, restart?

Sorry for my question.
Thank you for your help.

**Comment by bedmanforever** [comment]
> > 
> 
> I have the same problem, I can't install this Add-On. @bedmanforever , please give better instruction for your solution above. We have 2 points:
> 
> 1. Add Buster Backport to our apt sources  - What I should do it?
> 2. Update libseccomp2 - Have I add all text to file /etc/apt/sources.list
> 
> And what is it next step, restart?
> 
> Sorry for my question. Thank you for your help.

You need to login to the host system via SSH or HomeAssistant "Terminal" Addon first. As soon as you are logged in, you can execute the following command:

`sudo vi /etc/apt/sources.list`

Add the following line to the file "backports repo"
`deb http://deb.debian.org/debian buster-backports main`
  
Execute the following commands to add GPG Keys
`gpg --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC`
`gpg --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138`
`gpg --export 04EE7237B7D453EC | sudo apt-key add -`
`gpg --export 648ACFD622F3D138 | sudo apt-key add -`
  
And finally install libseccomp from backports:
`sudo apt install -t buster-backports libseccomp-dev`

I hope this clarifies the process.

**Comment by andrejskorols** [comment]
Now looks more clearer.
But sorry, still have a question.
1. sudo vi /etc/apt/sources.list
Ок, the command performed and I started edit sources.list Right?
I have to add what? My fail looks:
![image](https://user-images.githubusercontent.com/65221962/186370656-9b603f11-2061-487d-a741-0c382a610ecf.png)

2. Add the following line to the file "backports repo"
Where is this file?

**Comment by bedmanforever** [comment]
> Now looks more clearer. But sorry, still have a question.
> 
> 1. sudo vi /etc/apt/sources.list
>    Ок, the command performed and I started edit sources.list Right?

Right
>    I have to add what? My fail looks:
>    ![image](https://user-images.githubusercontent.com/65221962/186370656-9b603f11-2061-487d-a741-0c382a610ecf.png)
Check if the following line exists and if not add it to the file and save it:
`deb http://deb.debian.org/debian buster-backports main`
> 2. Add the following line to the file "backports repo"
>    Where is this file?
That was a reference to the /etc/apt/sources.list file from above.

**Comment by jeremydthomas** [comment]
> > > 
> > 
> > 
> > I have the same problem, I can't install this Add-On. @bedmanforever , please give better instruction for your solution above. We have 2 points:
> > 
> > 1. Add Buster Backport to our apt sources  - What I should do it?
> > 2. Update libseccomp2 - Have I add all text to file /etc/apt/sources.list
> > 
> > And what is it next step, restart?
> > Sorry for my question. Thank you for your help.
> 
> You need to login to the host system via SSH or HomeAssistant "Terminal" Addon first. As soon as you are logged in, you can execute the following command:
> 
> `sudo vi /etc/apt/sources.list`
> 
> Add the following line to the file "backports repo" `deb http://deb.debian.org/debian buster-backports main`
> 
> Execute the following commands to add GPG Keys `gpg --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC` `gpg --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138` `gpg --export 04EE7237B7D453EC | sudo apt-key add -` `gpg --export 648ACFD622F3D138 | sudo apt-key add -`
> 
> And finally install libseccomp from backports: `sudo apt install -t buster-backports libseccomp-dev`
> 
> I hope this clarifies the process.

Just an FYI I had to do sudo apt update before the install line to get it to work.

**Comment by jeremydthomas** [comment]
> > > 
> > 
> > 
> > I have the same problem, I can't install this Add-On. @bedmanforever , please give better instruction for your solution above. We have 2 points:
> > 
> > 1. Add Buster Backport to our apt sources  - What I should do it?
> > 2. Update libseccomp2 - Have I add all text to file /etc/apt/sources.list
> > 
> > And what is it next step, restart?
> > Sorry for my question. Thank you for your help.
> 
> You need to login to the host system via SSH or HomeAssistant "Terminal" Addon first. As soon as you are logged in, you can execute the following command:
> 
> `sudo vi /etc/apt/sources.list`
> 
> Add the following line to the file "backports repo" `deb http://deb.debian.org/debian buster-backports main`
> 
> Execute the following commands to add GPG Keys `gpg --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC` `gpg --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138` `gpg --export 04EE7237B7D453EC | sudo apt-key add -` `gpg --export 648ACFD622F3D138 | sudo apt-key add -`
> 
> And finally install libseccomp from backports: `sudo apt install -t buster-backports libseccomp-dev`
> 
> I hope this clarifies the process.

Make sure you ```sudo apt update``` before the install command. Only way I got it to work after adding the other stuff.

**Comment by user514** [comment]
Don't know if it will be published on a closed thread, but let me post the exact commands I have used to be able to install Simple Scheduler 0.64 (over my old 0.22 version).

  It is for a raspberry pi, so I think could help others with a raspi and a supervised installation on raspbian buster (which I think are many out there).

  -Uninstall Simple Scheduler from addons to avoid problems.

  -Enter to host raspberry using ssh (putty or whatecer). (enter to the host machine, not the 'Home Assistant command shell' from terminal&ssh addon).

  -Add repo keys:

`   # sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138`

  -Create (or edit if already exists) backport repo:

`  # nano /etc/apt/sources.list.d/debian-backports.list`

  -Add the line, to the file:
```
---
deb http://httpredir.debian.org/debian buster-backports main contrib non-free
---
```

  -Install libseccomp:
```
  # sudo apt-get update
  # sudo apt install -t buster-backports libseccomp-dev
```

(note1: in my case, it installed libseccomp-dev version 2.5.1-1 bpo10+1 and also upgrade libseccomp2 from version: 2.3.3-4 to version 2.5.1-1 bpo10+1)

(note2: you can check which you have installed with: 'sudo apt-cache policy libseccomp-dev' or 'sudo apt-cache policy libseccomp2' to check yours before and after).

(note3: In my case I had an 'UNHEALTHY' installation of HA, because of having portainer installer and before next step I needed to stop 'portainer' to be able to install any addon or update HA, but that's another story...)

  If you don't have Simple Scheduler repo added, add it: addons -> add repo -> https://github.com/arthurdent75/SimpleScheduler -> ADD -> REFRESH repo page or you wouldn't see it -> Simple scheduler 0.64 -> INSTALL.

  Done. Hope it helps someone.
