### ISSUE TITLE
Jobs running 1 hour before due time.

### ISSUE THREAD

**Issue by jbcorreia72** [arthurdent75/SimpleScheduler#71]
After the last update scheduling is occuring 1 h before the correct time.

Timezone is scorrectly set. It started running jobs at the wrong time a couple of days ago.

Refering to the following picture, job runs at 22:00 rather than at 23:00.

![image](https://user-images.githubusercontent.com/104595799/174169468-239eb187-7664-4c28-9f14-74b72ea0d720.png)

Thanks for any help you can provide.

**Comment by arthurdent75** [comment]
Attempt 1: Try to rebuild the addon.
![image](https://user-images.githubusercontent.com/60071192/174425182-45d722ec-5ac7-43d0-a15c-478bae9be7d8.png)

If it doesn't work...
Attempt 2: uninstall and reinstall the addon.


If it doesn't work...
Attempt 3: (If you have the _samba share_ addon installed) delete the _sun.dat_ file from the _\share\simplescheduler_ folder and restart the addon. Check also if the file is recreated.

**Comment by jbcorreia72** [comment]
Thank you so much. Working fine now.
