### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by Deinjo** [arthurdent75/SimpleScheduler#73]
Hi,

i have added the repo and then i tried to install the AddOn.
But i get an error message with the following content:
_The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends apache2 php7.4 php7.4-curl php7.4-intl php7.4-mbstring php7.4-json' returned a non-zero code: 100_

**Comment by arthurdent75** [comment]
Take a look here: https://github.com/arthurdent75/SimpleScheduler/issues/65#issuecomment-1141869405
