### ISSUE TITLE
Allow non admin users to view panel

### ISSUE THREAD

**Issue by acseven** [arthurdent75/SimpleScheduler#74]
[Hi,

Great work on this addon, thank you. 

I have one significant issue that is non admin users cannot open the addon. For what I've checked it's because you have the `panel_admin` variable set to true on `config.json`. 

Can you make this at least configurable, or even set it to false?

Reference info for this:
https://github.com/home-assistant/frontend/issues/5907#issuecomment-857764069

Regards

**Comment by arthurdent75** [comment]
Past in the days, this was not possible for any addon.
I read the link. I will try again now.

**Comment by acseven** [comment]
Hi, thanks for the reply. I've forked the repo and can confirm that with that setting non-admin users can access the addon. I have it working like that now, but it would be great if it could be configurable somehow!
Thank you

**Comment by arthurdent75** [comment]
Thank you for your contribution.
I had a lot of work on the last releases, so I'm taking a little break from this.
I will fix all the open issues ASAP.
Thanks again!

**Comment by arthurdent75** [comment]
Fixed in 0.61

**Comment by acseven** [comment]
thank you!!

**Comment by midadami** [comment]
Is it possible this is a problema once again? My configuration might be the problem so in case its not an addon problem just ignore it. Thanks
