### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by acseven** [arthurdent75/SimpleScheduler#75]
Hi again,

I appear to be having an issue with the Scheduler and timezones - maybe due to daylight saving times ? - and I've reviewed your suggestions in the readme.

SimpleScheduler status reports the same timezone as set in HA's settings:
![image](https://user-images.githubusercontent.com/1176371/182600136-1a81635f-d847-40e2-bd54-80e35e6e7634.png)

![image](https://user-images.githubusercontent.com/1176371/182600235-09de9f26-b187-41c0-9eb5-e60d0b6b7409.png)

However the schedules are activating one hour before they should. Also, in the logs, there's a two hour UTC delay which I can't relate to anything else. 

Can't seem to figure out what's wrong here. Any ideas?

**Comment by jmvaz** [comment]
Same problem here. https://community.home-assistant.io/t/simple-scheduler-addon/174326/276?u=jmvaz
I did a workaround, but sometimes it starts to happening again. I think is some race condition on homeassistant startup.

**Comment by acseven** [comment]
Just adding one additional comment: 
![image](https://user-images.githubusercontent.com/1176371/183529466-fb5df505-8153-47df-a731-ad517db45729.png)
This timestamp is wrong but the echo occurs before HASSOS's timezone is applied; after that I've checked the timezone is correct, coinciding with HA's config.

In any case, it still isn't working properly and I don't know why. 


> Same problem here. https://community.home-assistant.io/t/simple-scheduler-addon/174326/276?u=jmvaz I did a workaround, but sometimes it starts to happening again. I think is some race condition on homeassistant startup.

In my case I don't have that error on my logs.

**Comment by acseven** [comment]
Now it's getting weirder. Today's schedule's are working all on par. The only thing I think happened yesterday was upgrading to 2022.8.3 (and in respect, rebooting HA core).

**Comment by acseven** [comment]
Also, debug log is filled with these:

```
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/lib.php on line 61
Warning: Invalid argument supplied for foreach() in /var/www/html/lib.php on line 61
[Thu, 11 Aug 2022 22:00:00 +0100] SCHED:  switch/turn_on {"entity_id":"switch.knx_sr_1"} 
[Thu, 11 Aug 2022 22:03:00 +0100] SCHED:  switch/turn_off {"entity_id":"switch.knx_sr_1"} 
[Fri, 12 Aug 2022 00:01:01 +0100] SCHED:  climate/turn_off {"entity_id":"climate.cabg3"} 
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/lib.php on line 130
Notice: Uninitialized string offset: 0 in /var/www/html/lib.php on line 130
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/lib.php on line 130
[Fri, 12 Aug 2022 00:01:02 +0100] SCHED:  climate/turn_off {"entity_id":"climate.gabg5"} 
Notice: Uninitialized string offset: 0 in /var/www/html/lib.php on line 130
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/lib.php on line 130
[Fri, 12 Aug 2022 00:01:03 +0100] SCHED:  climate/turn_off {"entity_id":"climate.gabg4"} 
```

**Comment by arthurdent75** [comment]
Hi guys, I just came back from the holidays.
I think all the issues are related because the HA API is not responding to the addon.
I have some clues about why this happens, but I have to run some tests.
Sorry for the inconvenience, please have some patience...

**Comment by acseven** [comment]
No worries, thanks for having a look!

**Comment by acseven** [comment]
> Now it's getting weirder. Today's schedule's are working all on par. The only thing I think happened yesterday was upgrading to 2022.8.3 (and in respect, rebooting HA core).

Well, schedules are off again with no configuration modifications. I can't really find a pattern on this. :-/

**Comment by arthurdent75** [comment]
Should be fixed in 0.62
If not, I will reopen the issue

**Comment by acseven** [comment]
So far so good, I'll get back to you if it fails again. 

One detail though, these warning are still all over the place:

```
[Sun, 28 Aug 2022 00:01:01 +0100] SCHED:  climate/turn_off {"entity_id":"climate.redacted_climate_entity"} 
Notice: Uninitialized string offset: 0 in /var/www/html/lib.php on line 131
PHP Notice:  Uninitialized string offset: 0 in /var/www/html/lib.php on line 131
```

**Comment by arthurdent75** [comment]
> One detail though, these warnings are still all over the place:

Do you have debug enabled in the addon configuration?
Otherwise, you should not see _PHP Notice_ just _PHP Errors_

**Comment by acseven** [comment]
I did, my bad.

Thanks again


No dia 28/08/2022, às 10:04, arthurdent75 ***@***.***> escreveu:

﻿

One detail though, these warnings are still all over the place:

Do you have debug enabled in the addon configuration?
Otherwise, you should not see PHP Notice just PHP Errors
