### ISSUE TITLE
Feature request: Absolute brightness 

### ISSUE THREAD

**Issue by micw** [arthurdent75/SimpleScheduler#76]
Hello,

I use the scheduler for my garden watter where I use the "light" component on homeassistant (the absolute "brightness" is used as minutes).

![image](https://user-images.githubusercontent.com/186753/184508341-b4d1ddc3-5ce5-44dc-80fe-d2444b4a4005.png)

It would be great if I can set the brightness as absolute value in the schedule too (not only as percentual value). Also a custom unit ("minutes" in my case) + a custom icon (instead of the lamp icon) would be great.

**Comment by micw** [comment]
Suggestion:

`16:30>BA123` for Brightness absolute

`16:30>BA123;unit=min;icon=hass:water` for unit and icon

**Comment by arthurdent75** [comment]
Hi @micw 
thanks for your suggestions.
I believe this is a redundant feature because it won't add anything that is missing.
It is easier to think in terms of percent (0-100) instead of byte (0-255), so I don't get the advantage in that...

The icon is an interesting feature, but IMHO I think that the time will become difficult to read in case of two or more hours (besides the effort to implement it).

**Comment by micw** [comment]
My devices uses absolute ranges from 0..120 (I'm using brightness_scale in the entity definition in HA). The percentage is always based on 255 as maximum. With percentual settings, this always leeds to wrong values.

Other extensions to HA (like https://github.com/thomasloven/lovelace-slider-entity-row) make this work properly by allowing to set brigthness as absolute value rather than percentual.

I'd create a PR for the feature if you'd be open to merge it ;-)

**Comment by micw** [comment]
@arthurdent75 Please have a look to the PR above. I could achive my goal (except the icon stuff) with minimal changes.

**Comment by arthurdent75** [comment]
Didn't knew there are some devices that use max level other than 255

> Suggestion:
> 
> `16:30>BA123` for Brightness absolute

I will use this syntax.
It will be included in the next release

**Comment by arthurdent75** [comment]
Included in version 0.64
