### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by dubhunter** [arthurdent75/SimpleScheduler#8]
```
Warning: Unknown: failed to open stream: Permission denied in Unknown on line 0

Fatal error: Unknown: Failed opening required '/var/www/html/index.php' (include_path='.:/usr/local/lib/php') in Unknown on line 0
```

**Comment by arthurdent75** [comment]
Something went wrong during the installation.
All those "unknow" indicate that something in docker build didn't work as expected, e.g. the path where it is trying to search the include file. This doesn't seem to be related to my addon.
Try to remove it and reinstall it.
Do you have a customized install of HomeAssistant?

**Comment by dubhunter** [comment]
I don't think I have a customized install of Home Assistant. I am using the Hass.io Synology Package.

I tried to remove and reinstall, but getting the same error.

**Comment by shisva** [comment]
Hi, same issue with synology HAss.io package

path seems correct : 
![snip_20200503105255](https://user-images.githubusercontent.com/61910581/80909908-4e4d7d00-8d2c-11ea-92bc-ae47744bdced.png)

logs:
![Sans titre](https://user-images.githubusercontent.com/61910581/80909995-f4998280-8d2c-11ea-9266-e5e1fdaf0164.png)
