### ISSUE TITLE
MQTT switches are not removed when the Add-on is closed, subsequent restart creates switches ending with _2

### ISSUE THREAD

**Issue by maurizioandreotti60** [arthurdent75/SimpleScheduler#80]
I stopped the Add-on and the MQTT swithes were still available. After 10 minutes I can se the MQTT switches still alive.
I started the Add-on and the first original MQTT switch was still alive with the original name, while the other switches disappered substitued by _2 swithches.
If I restart the Add-on, all the original switches disappeared substited by _2 ones.
Only a further restart will fix the issue.

**Comment by arthurdent75** [comment]
Version 0.64 should fix this

**Comment by maurizioandreotti60** [comment]
I confirm that issue is fixed!
Thanks

**Comment by arthurdent75** [comment]
Glad to hear that. I'm closing the issue. Thanks.
