### ISSUE TITLE
Scheduler Times Activate 4 hours Prior Actual Scheduled Time

### ISSUE THREAD

**Issue by comet424** [arthurdent75/SimpleScheduler#81]
i having issues my schedule timers are off..   they are off by 4 hours

so if something supposed to come on at 4:23am  it comes on at 12:00am

or at 7pm  it comes on at 3pm   
the times are fine  HA  reports the right time.. on the bottom of the page for the simple scheduler  says  the proper time zone..
i have tried several reboots  a host reboot..   nothing fixing it   
is there something wrong with HA  or the scheduler.. is there something i need to change?

**Comment by arthurdent75** [comment]
Please paste the log here

**Comment by comet424** [comment]
Full logs
[Sun, 04 Sep 2022 04:25:24 +0000] Starting MQTT Listner...
[Sun, 04 Sep 2022 04:25:24 +0000] Starting scheduler...
[Sun, 04 Sep 2022 06:00:00 +0000] SCHED:  switch/turn_off {"entity_id":"switch.h_living_room_light"} 
[Sun, 04 Sep 2022 07:00:00 +0000] SCHED:  switch/turn_off {"entity_id":"switch.b_chest_freezer_1"} 
[Sun, 04 Sep 2022 07:00:00 +0000] SCHED:  switch/turn_off {"entity_id":"switch.b_back_freezer"} 
[Sun, 04 Sep 2022 07:00:00 +0000] SCHED:  switch/turn_off {"entity_id":"switch.b_cubical_freezer"} 
[Sun, 04 Sep 2022 07:00:00 +0000] SCHED:  switch/turn_off {"entity_id":"switch.b_chest_freezer_2"} 
[Sun, 04 Sep 2022 15:00:00 +0000] SCHED:  switch/turn_on {"entity_id":"switch.b_back_freezer"} 
[Sun, 04 Sep 2022 15:00:00 +0000] SCHED:  switch/turn_on {"entity_id":"switch.b_cubical_freezer"} 
[Sun, 04 Sep 2022 15:00:00 +0000] SCHED:  switch/turn_on {"entity_id":"switch.b_chest_freezer_2"} 
[Sun, 04 Sep 2022 19:00:00 +0000] SCHED:  switch/turn_on {"entity_id":"switch.b_chest_freezer_1"}

**Comment by comet424** [comment]
so [Sun, 04 Sep 2022 07:00:00 +0000] SCHED: switch/turn_off {"entity_id":"switch.b_cubical_freezer"}
just turned on 
Turned on triggered by service switch.turn_on
3:00:01 PM - 14 minutes ago - Supervisor

**Comment by comet424** [comment]
also the sunrise sunset is wrong  
on the simple scheduler page 
Sunrise 00:58 Sunset 14:18 TZ: America/Toronto Scheduler: RUNNING

says sunrse is at 1am  and sunset is at 2pm  so something wrong there too

**Comment by arthurdent75** [comment]
Are you using the latest version (0.64)?

**Comment by comet424** [comment]
no current version is  0.50    but auto update is set and there hasnt been an update in a while  showing in HA

**Comment by comet424** [comment]
![scheduler](https://user-images.githubusercontent.com/75998611/188460557-27d74c1b-e3cf-4285-ae3c-f5165a332c3e.PNG)
all other apps auto update  or when i gotta update through HACS so i know internet gets to it

**Comment by comet424** [comment]
for the one light that was set for 04:23 and shut off at 07:00    i had added 4 hours  so it be 08:23   
what i found it then worked for 8:23  didnt come on at 4:23  so a resave of the schedule fixed i guess.. not sure why?
and still no update option for Simple Scheduler...    there is a Rebuild button what does that do didnt wanna press it if it buggers up my schedules

**Comment by arthurdent75** [comment]
There was some bug with the timezone in the older version (see the changelog) so update the addon in the first place.
It is very odd that you don't get the update advice.

If you don't get any update, just remove the addon (maybe the repository too) and install it again.

**Comment by comet424** [comment]
ah ok ill try the remove and reinstall.. do you know what the  "rebuild" button does?   does it bugger up the timers i already made.. or is the rebuild button a force update?  i didnt wanna press it i didnt know what it did

**Comment by arthurdent75** [comment]
No, the rebuild button rebuilds the docker image of the file you have already downloaded.

**Comment by comet424** [comment]
ah ok  
so i uninstalled it.. gave me an error... fetch error  i went back to the add on store.. and clicked simple scheduler  same...   fetch error..   i do not know how to remove the repository...  is there a button for that too?

**Comment by comet424** [comment]
i re added the repository.. i noticed this lots..   HA seems to delete the Repositories.. your Simple Schulder  wasnt in there.. is that why it wasnt getting the updates?   its in the Addon store  but its not part of the repository.. i have had to do that before re put it in i remember several times in past for other programs..  
do you know why HA  removes them?  and is that why HA didnt update Scheduler as it wasnt part of the repository anymore

**Comment by arthurdent75** [comment]
Go to add-ons --> [add-on store] button
Once there, 3 dots in the top right --> repositories

**Comment by arthurdent75** [comment]
> do you know why HA removes them?

No

>and is that why HA didnt update Scheduler as it wasnt part of the repository anymore

Very likely

**Comment by comet424** [comment]
ok i stuck...    i had to restart home assistant to show the scheduler  in the add on store...  
i clicked the install.. but i got this error after a bit
The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends apache2 php7.4 php7.4-curl php7.4-intl php7.4-mbstring php7.4-json' returned a non-zero code: 100


do you know what that means?

**Comment by comet424** [comment]
4th time the charm it installed...  so lets hope it works today.. 
i appreciate the help..  ya probably cuz i loose the repository  its frustrating i know i had text file with the links to re add.. as i usually loose the community apps repository..

so fingers crossed things all work again (:

**Comment by arthurdent75** [comment]
> The command '/bin/bash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends apache2 php7.4 php7.4-curl php7.4-intl php7.4-mbstring php7.4-json' returned a non-zero code: 100
> 
> do you know what that means?

Yes
https://github.com/arthurdent75/SimpleScheduler/issues/65#issuecomment-1141869405

**Comment by comet424** [comment]
ah ok  cool.. o i checked  2 other HA setups i running  with your scheduler...  one was also stuck on .50 and other was stuck on 60
all 3 of my installs   lost the repository for your setup.. it has to do maybe when updating HA  it kicks it out..  you almost need it under HACS  maybe then HA wont kick it out?
going to reinstall  the other 2...   didnt even know it wasnt even checking for updates or updates were available go figure...  so hopefully by tomorrow   everything up and running  smoothly again (: 
and i really appreciate your app it helps so much

**Comment by arthurdent75** [comment]
I suspect that something in your docker setup is not update (hence the "returned a non-zero code" error) and somehow affect the repositories and the updates. 
BTW hope this will solve. Keep me posted

**Comment by comet424** [comment]
ah i dont know how to do docker setup?    i run  HA Supervisor 2 on Virtual Machines and 1 on a Raspberry Pi  so they the Supervisor Installs..    i  wouldnt even know where to look? 

and ok i let ya know..  and is there a log  that kicks out repositories?  i ment to check periodically..   but i forget to check

**Comment by arthurdent75** [comment]
Can you paste here the log of the 0.64 version?

**Comment by comet424** [comment]
so i thought it was working but glitched again..  here is log.
it doesnt show it..    but for the freezer seemed to be ok.. but ill find out today..

but the H_living_room light came on twice...    
its supposed to come on at 04:23 am   it actually came on twice

12:23am  and 04:23am  but it only registered once   so thats weird

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] simplescheduler: applying... 
[fix-attrs.d] simplescheduler: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 0.64
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.5  (amd64 / qemux86-64)
 Home Assistant Core: 2022.8.7
 Home Assistant Supervisor: 2022.08.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] simplescheduler.sh: executing... 
[10:54:52] INFO: Starting Scheduler
[cont-init.d] simplescheduler.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Mon, 05 Sep 2022 10:54:52 -0400] Starting scheduler...
[Mon, 05 Sep 2022 10:54:52 -0400] Home Assistant TimeZone: America/Toronto 
[Mon, 05 Sep 2022 10:54:52 -0400] Addon TimeZone: America/Toronto 
[10:54:52] INFO: Starting web server
[Mon, 05 Sep 2022 15:00:00 -0400] SCHED:  switch/turn_on {"entity_id":"switch.b_back_freezer"} 
[Mon, 05 Sep 2022 15:00:00 -0400] SCHED:  switch/turn_on {"entity_id":"switch.b_cubical_freezer"} 
[Mon, 05 Sep 2022 15:00:00 -0400] SCHED:  switch/turn_on {"entity_id":"switch.b_chest_freezer_2"} 
[Mon, 05 Sep 2022 19:00:00 -0400] SCHED:  switch/turn_on {"entity_id":"switch.b_chest_freezer_1"} 
[Tue, 06 Sep 2022 04:23:00 -0400] SCHED:  switch/turn_on {"entity_id":"switch.h_living_room_light"} 
[Tue, 06 Sep 2022 06:00:00 -0400] SCHED:  switch/turn_off {"entity_id":"switch.h_living_room_light"} 
[Tue, 06 Sep 2022 07:00:00 -0400] SCHED:  switch/turn_off {"entity_id":"switch.b_chest_freezer_1"} 
[Tue, 06 Sep 2022 07:00:00 -0400] SCHED:  switch/turn_off {"entity_id":"switch.b_back_freezer"} 
[Tue, 06 Sep 2022 07:00:00 -0400] SCHED:  switch/turn_off {"entity_id":"switch.b_cubical_freezer"} 
[Tue, 06 Sep 2022 07:00:00 -0400] SCHED:  switch/turn_off {"entity_id":"switch.b_chest_freezer_2"}

**Comment by comet424** [comment]
weird how it came on both times  and i dont get it..  a light switch shows up at turns on off.. but a plugs i have  it will show up turned on by service         how do i get light switchs to show up  as turned on by a service...    so you can disquinish between physical and like service when your scheduler turns it on

![scheduler2](https://user-images.githubusercontent.com/75998611/188661027-21d60bb0-e480-488a-b39a-b15e485ab628.PNG)

**Comment by comet424** [comment]
ah ok  ya  so things fixed itself.. i found the problem  why  i had issues of it still coming on at 12:23am  yet set for 04:23am  and i was running 64...  problem was 50 didnt uninstall properly in HA ..   it was still installed.. i had noticed  2 schedulers in the left side tab...  and in the Addons  there was 2  Schedulers...  50 and a 64...  it took a while to get the 50 uninstalled  between uninstall and restarting host,,  it just didnt wanna let go...  so it solved that... back to working again... really appreciate this application...  as i was having to write my own stuff before i learned  home assistant a few years ago

as for the turned on/off by service...  i checked.. all  my light switchs go by   turned on   off        but wifi plugs  go turned off on  by service...  i dont have any "light"    like  light.whatever     everything is    "switch.whatever"    but seems for Light switchs  it doesnt show up  as a service  in logs     probably a home Assistant issue?


so far ya  solved the issue now  2 schedulers were running  50 and 64... but working again (:   thanks

**Comment by arthurdent75** [comment]
> as for the turned on/off by service... i checked.. all my light switchs go by turned on off but wifi plugs go turned off on by service... i dont have any "light" like light.whatever everything is "switch.whatever" but seems for Light switchs it doesnt show up as a service in logs probably a home Assistant issue?

This is related to HA, cause I made the same call for both. There is nothing I can do about it.

**Comment by arthurdent75** [comment]
I think this issue can be closed.
