### ISSUE TITLE
Use for example lux sensor to control (condition) light

### ISSUE THREAD

**Issue by rhoddan** [arthurdent75/SimpleScheduler#84]
Thanks for a great addon. It would be great to be able to use a binary sensor or even better a number so I can control the lights with the real light outside (I have a lux sensor)

**Comment by arthurdent75** [comment]
Instead to set the light as the device inside the scheduler, create a script that turns on the light based on the lux sensor, and set the script as the device inside the scheduler.

But if you want the light to change its brightness while it is on dynamically based on the lux sensor, then you need to create an automation.
