### ISSUE TITLE
One-time action

### ISSUE THREAD

**Issue by dotnetniet** [arthurdent75/SimpleScheduler#88]
Hi,

Like the add-on, very useful for the less technical people.
Is it possible to add the following feature?

Sometimes we want to turn on or off a device only once. After it's turned on or off at the given time, the time can be removed/disabled. If there is no time left or it was the last time for the device, the schedule can be disabled.

Hope this makes any sense.

Thanks,
Mark

**Comment by arthurdent75** [comment]
Hi @dotnetniet 
I understand what you ask, but what you ask is something very far from the idea of a "scheduler"
I had this need too, but I solved it with a script that takes the entity id and the duration from a dropdown and a slider in the frontend. 
Sorry!
