### ISSUE TITLE
Sunrire, sunset object error

### ISSUE THREAD

**Issue by MahuteG** [arthurdent75/SimpleScheduler#89]
Hello,

may there is some trouble in the below lines

Notice: Trying to get property 'next_setting' of non-object in /var/www/html/lib.php on line 326

Notice: Trying to get property 'next_rising' of non-object in /var/www/html/lib.php on line 327

**Comment by arthurdent75** [comment]
This is not an issue. You can read these notices (not errors) because the debug mode is enabled.
