### ISSUE TITLE
Feature request;  Lock Unlock? 

### ISSUE THREAD

**Issue by Klagio** [arthurdent75/SimpleScheduler#9]
Is it possible to add?

Thanks!

**Comment by arthurdent75** [comment]
Can you be more specific? 😄

**Comment by Klagio** [comment]
Well a LIGHT is "on" and "off"

A LOCK is: "lock" and "unlock"

I do like to schedule my doors to be locked at 11pm, in case members of the family forgot to lock the doors, also my garage door as well. 

I do have 5 locks in my house, of course I can do automation or scripts, but would be a nice addon to have it in your already great scheduler

**Comment by Klagio** [comment]
Also 

cover.close_cover
and
cover.open_cover

**Comment by arthurdent75** [comment]
Ok, it is clear now.
No, those services aren't supported.
It only work with components which have **xxxx.turn_on** and **xxxx.turn_off** services.
The addon would be almost completely rewritten to support other services.
