### ISSUE TITLE
v2.0 Installation Fails

### ISSUE THREAD

**Issue by coolspot18** [arthurdent75/SimpleScheduler#93]
Hi,

I'm getting the following error with v2.0, the installer won't uprade and won't run. I've uninstalled the previous version and it still won't install:

Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 9:51:53 PM (1 occurrences)
Last logged: 9:51:53 PM

Failed to to call /addons/00185a40_simplescheduler/install - ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by arthurdent75** [comment]
Sorry guys, I just found out that there are different permission when the add-on is installed from the online repository vs local installation.
Just be patient, I'm trying to figure it out.

**Comment by arthurdent75** [comment]
Solved

**Comment by coolspot18** [comment]
> Sorry guys, I just found out that there are different permission when the add-on is installed from the online repository vs local installation. Just be patient, I'm trying to figure it out.

Just a FYI, I restored my HA instance and 0.64 was part of the restore bundle. 

0.64 would not run on the restored instance of HA, it displayed a bunch of chown errors.

**Comment by arthurdent75** [comment]
> Just a FYI, I restored my HA instance and 0.64 was part of the restore bundle.
> 
> 0.64 would not run on the restored instance of HA, it displayed a bunch of chown errors.

I know, there is already an issue open #96 
I hope to fix ASAP the 2.0
