### ISSUE TITLE
Cannot access the Web UI

### ISSUE THREAD

**Issue by jcoenencom** [arthurdent75/SimpleScheduler#95]
On a raspberry 3 HAOS latest version 

Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
user interface : 20221108.0 - latest

Updated from version 0.64 into the newest (2.04), lost access to the Web UI.
Recompiled, same thing
Remove and reinstalled, same thing

Calling the GUI comes back with 502: Bad Gateway error message.

Debug on, the log seems to indicate some kind of problem, but given the previous reported access rights problem, it sounds related.

I re-activated my FHEM weekday timers to prevent loss of service, so no fuss.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 2.0.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (armv7 / raspberrypi3)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun interface (no readiness notification)
services-up: info: copying legacy longrun scheduler (no readiness notification)
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise interface (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise interface (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise interface (child): fatal: unable to exec run: Permission denied

**Comment by sdoualle** [comment]
Dear all
Same issue for me

Home Assistant 2022.11.4
Supervisor 2022.11.2
Interface utilisateur : 20221108.0 - latest

Tried to uninstall and reinstall -> same thing

Thank you
SD

**Comment by Hilzi1984** [comment]
Hello,

Same here on Raspberry Pi 4B:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Simple Scheduler
 Simple timer on weekly base
-----------------------------------------------------------
 Add-on version: 2.0.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun interface (no readiness notification)
services-up: info: copying legacy longrun scheduler (no readiness notification)
s6-supervise interface (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise interface (child): fatal: unable to exec run: Permission denied
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise interface (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise interface (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds

**Comment by aunruh26** [comment]
Dear all.

I must confirm, same Issue here.

 Home Assistant 2022.11.4 
 Supervisor 2022.11.2 
 Operating System 9.3 
 Frontend 20221108.0 - latest 
 
Simple Scheduler: Current version: 2.0.4

Tried to: Uninstall / Install again; rebuild, rebuild. Everything without success.....


Add-on version: 2.0.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.3  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.4
 Home Assistant Supervisor: 2022.11.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun interface (no readiness notification)
services-up: info: copying legacy longrun scheduler (no readiness notification)
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise interface (child): fatal: unable to exec run: Permission denied
s6-supervise scheduler: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise scheduler (child): fatal: unable to exec run: Permission denied
s6-supervise interface: warning: unable to spawn ./run - waiting 10 seconds

Thx and BRGDS // André

**Comment by arthurdent75** [comment]
Duplicate #92
