### ISSUE TITLE
Up/downgrade to 0.64 fails

### ISSUE THREAD

**Issue by Bubi504** [arthurdent75/SimpleScheduler#96]
After the well-known (unsuccessful) upgrade to v2.0, the v0.64 build fails : 

22-11-30 14:15:01 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for 00185a40/amd64-addon-simplescheduler:0.64
22-11-30 14:15:25 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build 00185a40/amd64-addon-simplescheduler:0.64: The command '/bin/ash -o pipefail -c apt-get update     && apt-get install -y --no-install-recommends		apache2 		php7.4 		php7.4-curl 		php7.4-intl 		php7.4-mbstring 		php7.4-json' returned a non-zero code: 127
22-11-30 14:15:25 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/10 : ARG BUILD_FROM=ghcr.io/hassio-addons/debian-base/amd64:5.3.0
Step 2/10 : FROM ${BUILD_FROM}
 ---> 3d24a9ac8a30
Step 3/10 : RUN     apt-get update     && apt-get install -y --no-install-recommends		apache2 		php7.4 		php7.4-curl 		php7.4-intl 		php7.4-mbstring 		php7.4-json
 ---> Running in cbb23a46abfe
/bin/ash: apt-get: not found

**Comment by arthurdent75** [comment]
No clue. I just put the old version there.
Leave this open just to avoid duplicates, but there is no point in solving it because 0.64 will be replaced by 2.0

**Comment by mscosta01** [comment]
The best solution I found, because the new version didn't work and I couldn't downgrade to 0.64, because of the error, was to do a partial replacement of the add-on using a recent HA backup...

**Comment by meuch13** [comment]
I believe the downgrade does not work because of the build.yaml changed from the 5.3.0 tag to latest. Might be wrong, didn't check the difference on the container build.

**Comment by CobraXLazer** [comment]
Have the same issue! Can't install 0.64/2.0. Need it so bad. The best add on for HA.  📣

**Comment by arthurdent75** [comment]
I've just published a new temporary version, quickly built on a different base image.
In this version the log doesn't appear in the addon log section (but you can read them from the _simplescheduler.log_ file in the _share_ folder).  Also, the processes are not running as a daemon, so in case of crash they won't respawn (but they never crashed in one month of testing)
I repeat: this is temporary, meanwhile I am trying to figure out why the official docker container for HA addons doesn't work. It's just a quick fix for those who got stuck...

**Comment by Bubi504** [comment]
Thanks a lot, it's working !

**Comment by LunaticSerenade** [comment]
thanks for the quick fix!

**Comment by arthurdent75** [comment]
I revert the repository to the working 0.64.
Meanwhile, I hope that someone from the developer team would help me.

**Comment by arthurdent75** [comment]
If you are an HA advanced user and you want to try the new release 2.0 as beta tester add this repository:

https://github.com/arthurdent75/SimpleScheduler-BETA
