### ISSUE TITLE
Cannot reinstall

### ISSUE THREAD

**Issue by PKOE05** [arthurdent75/SimpleScheduler#98]
After installing V2.04 and running in error 502 I uninstalled V2.04 and removed the repository "Simple Scheduler". Restart of HA.

Added repository again (in the meantime 0.64) and tried to install:

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 20:29:50 (1 occurrences)
Last logged: 20:29:50

Failed to to call /addons/00185a40_simplescheduler/install - The command '/bin/ash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends apache2 php7.4 php7.4-curl php7.4-intl php7.4-mbstring php7.4-json' returned a non-zero code: 127

Now I have no scheduler at all.

Running on:
   Home Assistant 2022.11.5
   Supervisor 2022.11.2
   Operating System 9.3
   Frontend 20221108.0 - latest

**Comment by akalderon** [comment]
Same

**Comment by coolspot18** [comment]
In the mean time, I'm using Scheduler Card and Scheduler Component - I still prefer Simple Scheduler, but it'a pretty good, solid, stop gap until Simple Scheduler is fixed.

**Comment by arthurdent75** [comment]
duplicate #96
