### ISSUE TITLE
Installation failed || v 0.64 || HAOS

### ISSUE THREAD

**Issue by TeleporterGuy** [arthurdent75/SimpleScheduler#99]
Hi,
I tried installing your scheduler on Supervised Home Assistant (running in VM in Synology NAS) and got following error:
Failed to install add-on
The command '/bin/ash -o pipefail -c apt-get update && apt-get install -y --no-install-recommends apache2 php7.4 php7.4-curl php7.4-intl php7.4-mbstring php7.4-json' returned a non-zero code: 127

System info:
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

Let me know if I can provide additional information

**Comment by arthurdent75** [comment]
Duplicate #96
